// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notify.sql

package store

import (
	"context"
	"time"
)

const getNotificationLog = `-- name: GetNotificationLog :one
SELECT id, status, attempts
FROM notification_logs
WHERE id = $1
`

type GetNotificationLogRow struct {
	ID       int64
	Status   string
	Attempts int16
}

func (q *Queries) GetNotificationLog(ctx context.Context, id int64) (GetNotificationLogRow, error) {
	row := q.db.QueryRow(ctx, getNotificationLog, id)
	var i GetNotificationLogRow
	err := row.Scan(&i.ID, &i.Status, &i.Attempts)
	return i, err
}

const getNotifyRecipient = `-- name: GetNotifyRecipient :one
SELECT telegram_user_id, locale
FROM users
WHERE id = $1
`

type GetNotifyRecipientRow struct {
	TelegramUserID *int64
	Locale         string
}

func (q *Queries) GetNotifyRecipient(ctx context.Context, id int64) (GetNotifyRecipientRow, error) {
	row := q.db.QueryRow(ctx, getNotifyRecipient, id)
	var i GetNotifyRecipientRow
	err := row.Scan(&i.TelegramUserID, &i.Locale)
	return i, err
}

const insertNotificationLog = `-- name: InsertNotificationLog :one
INSERT INTO notification_logs (channel, recipient, template, locale, entity_type, entity_id, dedupe_key)
VALUES ('TELEGRAM', $1, $2, $3, 'reg_order', $4, $5)
ON CONFLICT (dedupe_key) DO NOTHING
RETURNING id
`

type InsertNotificationLogParams struct {
	Recipient string
	Template  string
	Locale    string
	EntityID  *int64
	DedupeKey string
}

func (q *Queries) InsertNotificationLog(ctx context.Context, arg InsertNotificationLogParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertNotificationLog,
		arg.Recipient,
		arg.Template,
		arg.Locale,
		arg.EntityID,
		arg.DedupeKey,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const markNotificationAttemptFailed = `-- name: MarkNotificationAttemptFailed :exec
UPDATE notification_logs
SET status = $1, attempts = attempts + 1, last_error = $2
WHERE id = $3
`

type MarkNotificationAttemptFailedParams struct {
	Status    string
	LastError *string
	ID        int64
}

func (q *Queries) MarkNotificationAttemptFailed(ctx context.Context, arg MarkNotificationAttemptFailedParams) error {
	_, err := q.db.Exec(ctx, markNotificationAttemptFailed, arg.Status, arg.LastError, arg.ID)
	return err
}

const markNotificationSent = `-- name: MarkNotificationSent :exec
UPDATE notification_logs
SET status = 'SENT', sent_at = $1, attempts = attempts + 1, last_error = NULL
WHERE id = $2
`

type MarkNotificationSentParams struct {
	SentAt *time.Time
	ID     int64
}

func (q *Queries) MarkNotificationSent(ctx context.Context, arg MarkNotificationSentParams) error {
	_, err := q.db.Exec(ctx, markNotificationSent, arg.SentAt, arg.ID)
	return err
}
