// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment.sql

package store

import (
	"context"
)

const eventExists = `-- name: EventExists :one
SELECT EXISTS (SELECT 1 FROM events WHERE id = $1)
`

func (q *Queries) EventExists(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, eventExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getPaymentAccountForUpdate = `-- name: GetPaymentAccountForUpdate :one
SELECT id, name, provider, account_name, account_no_masked, currency, qr_file_id, scope, event_id, active, created_by, created_at FROM payment_accounts
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetPaymentAccountForUpdate(ctx context.Context, id int64) (PaymentAccount, error) {
	row := q.db.QueryRow(ctx, getPaymentAccountForUpdate, id)
	var i PaymentAccount
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.AccountName,
		&i.AccountNoMasked,
		&i.Currency,
		&i.QrFileID,
		&i.Scope,
		&i.EventID,
		&i.Active,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const insertPaymentAccount = `-- name: InsertPaymentAccount :one
INSERT INTO payment_accounts (name, provider, account_name, account_no_masked, currency, qr_file_id,
                              scope, event_id, active, created_by)
VALUES ($1, $2, $3, $4, 'USD', $5,
        $6, $7, $8, $9)
RETURNING id, name, provider, account_name, account_no_masked, currency, qr_file_id, scope, event_id, active, created_by, created_at
`

type InsertPaymentAccountParams struct {
	Name            string
	Provider        string
	AccountName     string
	AccountNoMasked string
	QrFileID        int64
	Scope           string
	EventID         *int64
	Active          bool
	CreatedBy       *int64
}

func (q *Queries) InsertPaymentAccount(ctx context.Context, arg InsertPaymentAccountParams) (PaymentAccount, error) {
	row := q.db.QueryRow(ctx, insertPaymentAccount,
		arg.Name,
		arg.Provider,
		arg.AccountName,
		arg.AccountNoMasked,
		arg.QrFileID,
		arg.Scope,
		arg.EventID,
		arg.Active,
		arg.CreatedBy,
	)
	var i PaymentAccount
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.AccountName,
		&i.AccountNoMasked,
		&i.Currency,
		&i.QrFileID,
		&i.Scope,
		&i.EventID,
		&i.Active,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listPaymentAccounts = `-- name: ListPaymentAccounts :many
SELECT id, name, provider, account_name, account_no_masked, currency, qr_file_id, scope, event_id, active, created_by, created_at FROM payment_accounts
ORDER BY active DESC, id
`

func (q *Queries) ListPaymentAccounts(ctx context.Context) ([]PaymentAccount, error) {
	rows, err := q.db.Query(ctx, listPaymentAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentAccount
	for rows.Next() {
		var i PaymentAccount
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Provider,
			&i.AccountName,
			&i.AccountNoMasked,
			&i.Currency,
			&i.QrFileID,
			&i.Scope,
			&i.EventID,
			&i.Active,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePaymentAccount = `-- name: UpdatePaymentAccount :one
UPDATE payment_accounts
SET name = $1,
    provider = $2,
    account_name = $3,
    account_no_masked = $4,
    currency = 'USD',
    qr_file_id = $5,
    scope = $6,
    event_id = $7,
    active = $8
WHERE id = $9
RETURNING id, name, provider, account_name, account_no_masked, currency, qr_file_id, scope, event_id, active, created_by, created_at
`

type UpdatePaymentAccountParams struct {
	Name            string
	Provider        string
	AccountName     string
	AccountNoMasked string
	QrFileID        int64
	Scope           string
	EventID         *int64
	Active          bool
	ID              int64
}

func (q *Queries) UpdatePaymentAccount(ctx context.Context, arg UpdatePaymentAccountParams) (PaymentAccount, error) {
	row := q.db.QueryRow(ctx, updatePaymentAccount,
		arg.Name,
		arg.Provider,
		arg.AccountName,
		arg.AccountNoMasked,
		arg.QrFileID,
		arg.Scope,
		arg.EventID,
		arg.Active,
		arg.ID,
	)
	var i PaymentAccount
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.AccountName,
		&i.AccountNoMasked,
		&i.Currency,
		&i.QrFileID,
		&i.Scope,
		&i.EventID,
		&i.Active,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}
