// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: registration.sql

package store

import (
	"context"
	"time"
)

const adminCountRegOrders = `-- name: AdminCountRegOrders :one
SELECT count(*)
FROM reg_orders o
WHERE ($1::bigint IS NULL OR o.event_id = $1::bigint)
  AND ($2::text = '' OR o.status = $2::text)
  AND ($3::text = ''
       OR o.order_no = upper($3::text)
       OR o.buyer_phone_e164 LIKE ('%' || $4::text || '%') ESCAPE '\'
       OR o.buyer_name ILIKE ('%' || $4::text || '%') ESCAPE '\')
`

type AdminCountRegOrdersParams struct {
	EventID *int64
	Status  string
	Q       string
	QLike   string
}

func (q *Queries) AdminCountRegOrders(ctx context.Context, arg AdminCountRegOrdersParams) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountRegOrders,
		arg.EventID,
		arg.Status,
		arg.Q,
		arg.QLike,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminGetOrderCoupon = `-- name: AdminGetOrderCoupon :one
SELECT c.code, cr.discount_cents, cr.state
FROM coupon_redemptions cr
JOIN coupons c ON c.id = cr.coupon_id
WHERE cr.order_id = $1
`

type AdminGetOrderCouponRow struct {
	Code          string
	DiscountCents int64
	State         string
}

func (q *Queries) AdminGetOrderCoupon(ctx context.Context, orderID int64) (AdminGetOrderCouponRow, error) {
	row := q.db.QueryRow(ctx, adminGetOrderCoupon, orderID)
	var i AdminGetOrderCouponRow
	err := row.Scan(&i.Code, &i.DiscountCents, &i.State)
	return i, err
}

const adminGetRegOrderBuyer = `-- name: AdminGetRegOrderBuyer :one
SELECT buyer_name, buyer_phone_e164
FROM reg_orders
WHERE id = $1
`

type AdminGetRegOrderBuyerRow struct {
	BuyerName      string
	BuyerPhoneE164 string
}

func (q *Queries) AdminGetRegOrderBuyer(ctx context.Context, id int64) (AdminGetRegOrderBuyerRow, error) {
	row := q.db.QueryRow(ctx, adminGetRegOrderBuyer, id)
	var i AdminGetRegOrderBuyerRow
	err := row.Scan(&i.BuyerName, &i.BuyerPhoneE164)
	return i, err
}

const adminListOrderProofs = `-- name: AdminListOrderProofs :many
SELECT id, proof_no, status, bank_txn_ref, declared_amount_cents, reject_code, created_at, reviewed_at
FROM payment_proofs
WHERE reg_order_id = $1::bigint
ORDER BY created_at DESC, id DESC
`

type AdminListOrderProofsRow struct {
	ID                  int64
	ProofNo             string
	Status              string
	BankTxnRef          string
	DeclaredAmountCents int64
	RejectCode          *string
	CreatedAt           time.Time
	ReviewedAt          *time.Time
}

func (q *Queries) AdminListOrderProofs(ctx context.Context, orderID int64) ([]AdminListOrderProofsRow, error) {
	rows, err := q.db.Query(ctx, adminListOrderProofs, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListOrderProofsRow
	for rows.Next() {
		var i AdminListOrderProofsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProofNo,
			&i.Status,
			&i.BankTxnRef,
			&i.DeclaredAmountCents,
			&i.RejectCode,
			&i.CreatedAt,
			&i.ReviewedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListOrderReceipts = `-- name: AdminListOrderReceipts :many
SELECT id, txn_ref, amount_cents, received_at, match_status
FROM payment_receipts
WHERE reg_order_id = $1::bigint
ORDER BY received_at, id
`

type AdminListOrderReceiptsRow struct {
	ID          int64
	TxnRef      string
	AmountCents int64
	ReceivedAt  time.Time
	MatchStatus string
}

func (q *Queries) AdminListOrderReceipts(ctx context.Context, orderID int64) ([]AdminListOrderReceiptsRow, error) {
	rows, err := q.db.Query(ctx, adminListOrderReceipts, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListOrderReceiptsRow
	for rows.Next() {
		var i AdminListOrderReceiptsRow
		if err := rows.Scan(
			&i.ID,
			&i.TxnRef,
			&i.AmountCents,
			&i.ReceivedAt,
			&i.MatchStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListRegOrders = `-- name: AdminListRegOrders :many
SELECT o.id, o.order_no, o.event_id, o.buyer_user_id, o.buyer_name, o.buyer_phone_e164, o.buyer_email, o.status, o.reservation_state, o.reservation_release_kind, o.list_amount_cents, o.discount_cents, o.ident_offset_cents, o.amount_cents, o.currency, o.coupon_id, o.payment_account_id, o.deadline_at, o.paid_at, o.expired_at, o.cancelled_at, o.cancel_reason, o.source, o.archived, o.version, o.created_at, o.updated_at,
       e.slug AS event_slug,
       e.name AS event_name,
       (SELECT count(*) FROM order_participants op WHERE op.order_id = o.id)::int AS participant_count
FROM reg_orders o
JOIN events e ON e.id = o.event_id
WHERE ($1::bigint IS NULL OR o.event_id = $1::bigint)
  AND ($2::text = '' OR o.status = $2::text)
  AND ($3::text = ''
       OR o.order_no = upper($3::text)
       OR o.buyer_phone_e164 LIKE ('%' || $4::text || '%') ESCAPE '\'
       OR o.buyer_name ILIKE ('%' || $4::text || '%') ESCAPE '\')
ORDER BY o.created_at DESC, o.id DESC
LIMIT $6::int OFFSET $5::int
`

type AdminListRegOrdersParams struct {
	EventID   *int64
	Status    string
	Q         string
	QLike     string
	RowOffset int32
	RowLimit  int32
}

type AdminListRegOrdersRow struct {
	RegOrder         RegOrder
	EventSlug        string
	EventName        []byte
	ParticipantCount int32
}

func (q *Queries) AdminListRegOrders(ctx context.Context, arg AdminListRegOrdersParams) ([]AdminListRegOrdersRow, error) {
	rows, err := q.db.Query(ctx, adminListRegOrders,
		arg.EventID,
		arg.Status,
		arg.Q,
		arg.QLike,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListRegOrdersRow
	for rows.Next() {
		var i AdminListRegOrdersRow
		if err := rows.Scan(
			&i.RegOrder.ID,
			&i.RegOrder.OrderNo,
			&i.RegOrder.EventID,
			&i.RegOrder.BuyerUserID,
			&i.RegOrder.BuyerName,
			&i.RegOrder.BuyerPhoneE164,
			&i.RegOrder.BuyerEmail,
			&i.RegOrder.Status,
			&i.RegOrder.ReservationState,
			&i.RegOrder.ReservationReleaseKind,
			&i.RegOrder.ListAmountCents,
			&i.RegOrder.DiscountCents,
			&i.RegOrder.IdentOffsetCents,
			&i.RegOrder.AmountCents,
			&i.RegOrder.Currency,
			&i.RegOrder.CouponID,
			&i.RegOrder.PaymentAccountID,
			&i.RegOrder.DeadlineAt,
			&i.RegOrder.PaidAt,
			&i.RegOrder.ExpiredAt,
			&i.RegOrder.CancelledAt,
			&i.RegOrder.CancelReason,
			&i.RegOrder.Source,
			&i.RegOrder.Archived,
			&i.RegOrder.Version,
			&i.RegOrder.CreatedAt,
			&i.RegOrder.UpdatedAt,
			&i.EventSlug,
			&i.EventName,
			&i.ParticipantCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const cancelOrderRegistrations = `-- name: CancelOrderRegistrations :execrows
UPDATE registrations r
SET status = 'CANCELLED', cancel_reason = $1::text, version = r.version + 1
FROM order_participants op
WHERE op.id = r.order_participant_id
  AND op.order_id = $2::bigint
  AND r.status = 'PENDING'
`

type CancelOrderRegistrationsParams struct {
	CancelReason string
	OrderID      int64
}

func (q *Queries) CancelOrderRegistrations(ctx context.Context, arg CancelOrderRegistrationsParams) (int64, error) {
	result, err := q.db.Exec(ctx, cancelOrderRegistrations, arg.CancelReason, arg.OrderID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimIdempotencyKey = `-- name: ClaimIdempotencyKey :one
INSERT INTO idempotency_keys (key, scope, subject, request_hash, created_at, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (scope, subject, key) DO UPDATE
SET request_hash = EXCLUDED.request_hash,
    response_code = NULL,
    response_body = NULL,
    created_at = EXCLUDED.created_at,
    expires_at = EXCLUDED.expires_at
WHERE idempotency_keys.expires_at <= EXCLUDED.created_at
RETURNING key
`

type ClaimIdempotencyKeyParams struct {
	Key         string
	Scope       string
	Subject     string
	RequestHash []byte
	Now         time.Time
	ExpiresAt   time.Time
}

// 新键直接插入；已过期的同名键被覆盖；未过期的同名键不返回行（并等待持有它的事务结束）。
func (q *Queries) ClaimIdempotencyKey(ctx context.Context, arg ClaimIdempotencyKeyParams) (string, error) {
	row := q.db.QueryRow(ctx, claimIdempotencyKey,
		arg.Key,
		arg.Scope,
		arg.Subject,
		arg.RequestHash,
		arg.Now,
		arg.ExpiresAt,
	)
	var key string
	err := row.Scan(&key)
	return key, err
}

const confirmOrderRegistrations = `-- name: ConfirmOrderRegistrations :execrows
UPDATE registrations r
SET status = 'CONFIRMED', confirmed_at = $1::timestamptz, version = r.version + 1
FROM order_participants op
WHERE op.id = r.order_participant_id
  AND op.order_id = $2::bigint
  AND r.status = 'PENDING'
`

type ConfirmOrderRegistrationsParams struct {
	ConfirmedAt time.Time
	OrderID     int64
}

func (q *Queries) ConfirmOrderRegistrations(ctx context.Context, arg ConfirmOrderRegistrationsParams) (int64, error) {
	result, err := q.db.Exec(ctx, confirmOrderRegistrations, arg.ConfirmedAt, arg.OrderID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const freeSignupGetCategory = `-- name: FreeSignupGetCategory :one
SELECT id, min_age
FROM event_categories
WHERE id = $1 AND event_id = $2
`

type FreeSignupGetCategoryParams struct {
	ID      int64
	EventID int64
}

type FreeSignupGetCategoryRow struct {
	ID     int64
	MinAge int16
}

func (q *Queries) FreeSignupGetCategory(ctx context.Context, arg FreeSignupGetCategoryParams) (FreeSignupGetCategoryRow, error) {
	row := q.db.QueryRow(ctx, freeSignupGetCategory, arg.ID, arg.EventID)
	var i FreeSignupGetCategoryRow
	err := row.Scan(&i.ID, &i.MinAge)
	return i, err
}

const freeSignupLockEvent = `-- name: FreeSignupLockEvent :one
SELECT id, event_type, status, registration_open, registration_opens_at, registration_closes_at, race_date
FROM events
WHERE slug = $1
FOR SHARE
`

type FreeSignupLockEventRow struct {
	ID                   int64
	EventType            string
	Status               string
	RegistrationOpen     bool
	RegistrationOpensAt  *time.Time
	RegistrationClosesAt *time.Time
	RaceDate             time.Time
}

func (q *Queries) FreeSignupLockEvent(ctx context.Context, slug string) (FreeSignupLockEventRow, error) {
	row := q.db.QueryRow(ctx, freeSignupLockEvent, slug)
	var i FreeSignupLockEventRow
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.Status,
		&i.RegistrationOpen,
		&i.RegistrationOpensAt,
		&i.RegistrationClosesAt,
		&i.RaceDate,
	)
	return i, err
}

const freeSignupTakeSeat = `-- name: FreeSignupTakeSeat :execrows
UPDATE event_categories
SET used_count = used_count + 1
WHERE id = $1 AND used_count + reserved_count + 1 <= capacity
`

func (q *Queries) FreeSignupTakeSeat(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, freeSignupTakeSeat, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getEventForQuote = `-- name: GetEventForQuote :one
SELECT id, event_type, status, race_date
FROM events
WHERE slug = $1
`

type GetEventForQuoteRow struct {
	ID        int64
	EventType string
	Status    string
	RaceDate  time.Time
}

func (q *Queries) GetEventForQuote(ctx context.Context, slug string) (GetEventForQuoteRow, error) {
	row := q.db.QueryRow(ctx, getEventForQuote, slug)
	var i GetEventForQuoteRow
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.Status,
		&i.RaceDate,
	)
	return i, err
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT request_hash, response_code, response_body
FROM idempotency_keys
WHERE scope = $1 AND subject = $2 AND key = $3
`

type GetIdempotencyKeyParams struct {
	Scope   string
	Subject string
	Key     string
}

type GetIdempotencyKeyRow struct {
	RequestHash  []byte
	ResponseCode *int32
	ResponseBody []byte
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (GetIdempotencyKeyRow, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, arg.Scope, arg.Subject, arg.Key)
	var i GetIdempotencyKeyRow
	err := row.Scan(&i.RequestHash, &i.ResponseCode, &i.ResponseBody)
	return i, err
}

const getLastRejectedProof = `-- name: GetLastRejectedProof :one
SELECT reject_code, reject_reason, reviewed_at
FROM payment_proofs
WHERE reg_order_id = $1::bigint AND status = 'REJECTED'
ORDER BY reviewed_at DESC, id DESC
LIMIT 1
`

type GetLastRejectedProofRow struct {
	RejectCode   *string
	RejectReason *string
	ReviewedAt   *time.Time
}

func (q *Queries) GetLastRejectedProof(ctx context.Context, regOrderID int64) (GetLastRejectedProofRow, error) {
	row := q.db.QueryRow(ctx, getLastRejectedProof, regOrderID)
	var i GetLastRejectedProofRow
	err := row.Scan(&i.RejectCode, &i.RejectReason, &i.ReviewedAt)
	return i, err
}

const getOrderDetailByID = `-- name: GetOrderDetailByID :one
SELECT o.id, o.order_no, o.event_id, o.buyer_user_id, o.status, o.reservation_state,
       o.list_amount_cents, o.discount_cents, o.ident_offset_cents, o.amount_cents, o.currency,
       o.payment_account_id, o.deadline_at, o.paid_at, o.created_at,
       e.slug AS event_slug, e.name AS event_name, e.timezone AS event_timezone
FROM reg_orders o
JOIN events e ON e.id = o.event_id
WHERE o.id = $1
`

type GetOrderDetailByIDRow struct {
	ID               int64
	OrderNo          string
	EventID          int64
	BuyerUserID      *int64
	Status           string
	ReservationState string
	ListAmountCents  int64
	DiscountCents    int64
	IdentOffsetCents int16
	AmountCents      int64
	Currency         string
	PaymentAccountID *int64
	DeadlineAt       *time.Time
	PaidAt           *time.Time
	CreatedAt        time.Time
	EventSlug        string
	EventName        []byte
	EventTimezone    string
}

func (q *Queries) GetOrderDetailByID(ctx context.Context, id int64) (GetOrderDetailByIDRow, error) {
	row := q.db.QueryRow(ctx, getOrderDetailByID, id)
	var i GetOrderDetailByIDRow
	err := row.Scan(
		&i.ID,
		&i.OrderNo,
		&i.EventID,
		&i.BuyerUserID,
		&i.Status,
		&i.ReservationState,
		&i.ListAmountCents,
		&i.DiscountCents,
		&i.IdentOffsetCents,
		&i.AmountCents,
		&i.Currency,
		&i.PaymentAccountID,
		&i.DeadlineAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.EventSlug,
		&i.EventName,
		&i.EventTimezone,
	)
	return i, err
}

const getOrderForExpiryNotice = `-- name: GetOrderForExpiryNotice :one
SELECT order_no, buyer_user_id, event_id, status, deadline_at
FROM reg_orders
WHERE id = $1
`

type GetOrderForExpiryNoticeRow struct {
	OrderNo     string
	BuyerUserID *int64
	EventID     int64
	Status      string
	DeadlineAt  *time.Time
}

func (q *Queries) GetOrderForExpiryNotice(ctx context.Context, id int64) (GetOrderForExpiryNoticeRow, error) {
	row := q.db.QueryRow(ctx, getOrderForExpiryNotice, id)
	var i GetOrderForExpiryNoticeRow
	err := row.Scan(
		&i.OrderNo,
		&i.BuyerUserID,
		&i.EventID,
		&i.Status,
		&i.DeadlineAt,
	)
	return i, err
}

const getOrderIDForBuyer = `-- name: GetOrderIDForBuyer :one
SELECT id
FROM reg_orders
WHERE order_no = $1 AND buyer_user_id = $2::bigint
`

type GetOrderIDForBuyerParams struct {
	OrderNo     string
	BuyerUserID int64
}

func (q *Queries) GetOrderIDForBuyer(ctx context.Context, arg GetOrderIDForBuyerParams) (int64, error) {
	row := q.db.QueryRow(ctx, getOrderIDForBuyer, arg.OrderNo, arg.BuyerUserID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getOrderPaymentAccount = `-- name: GetOrderPaymentAccount :one
SELECT id, name, provider, account_name, account_no_masked, qr_file_id
FROM payment_accounts
WHERE id = $1
`

type GetOrderPaymentAccountRow struct {
	ID              int64
	Name            string
	Provider        string
	AccountName     string
	AccountNoMasked string
	QrFileID        int64
}

func (q *Queries) GetOrderPaymentAccount(ctx context.Context, id int64) (GetOrderPaymentAccountRow, error) {
	row := q.db.QueryRow(ctx, getOrderPaymentAccount, id)
	var i GetOrderPaymentAccountRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.AccountName,
		&i.AccountNoMasked,
		&i.QrFileID,
	)
	return i, err
}

const insertFreeSignup = `-- name: InsertFreeSignup :one
INSERT INTO free_signups (
  signup_no, event_id, category_id, user_id, full_name, phone_e164,
  gender, birth_date, emergency_name, emergency_phone, source
) VALUES (
  $1, $2, $3, $4::bigint, $5, $6,
  NULLIF($7::text, ''), NULLIF($8::text, '')::date,
  $9::text, $10::text, 'TELEGRAM'
)
RETURNING id, signup_no, status, created_at
`

type InsertFreeSignupParams struct {
	SignupNo       string
	EventID        int64
	CategoryID     int64
	UserID         int64
	FullName       string
	PhoneE164      string
	Gender         string
	BirthDate      string
	EmergencyName  string
	EmergencyPhone string
}

type InsertFreeSignupRow struct {
	ID        int64
	SignupNo  string
	Status    string
	CreatedAt time.Time
}

func (q *Queries) InsertFreeSignup(ctx context.Context, arg InsertFreeSignupParams) (InsertFreeSignupRow, error) {
	row := q.db.QueryRow(ctx, insertFreeSignup,
		arg.SignupNo,
		arg.EventID,
		arg.CategoryID,
		arg.UserID,
		arg.FullName,
		arg.PhoneE164,
		arg.Gender,
		arg.BirthDate,
		arg.EmergencyName,
		arg.EmergencyPhone,
	)
	var i InsertFreeSignupRow
	err := row.Scan(
		&i.ID,
		&i.SignupNo,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const insertOrderParticipant = `-- name: InsertOrderParticipant :one
INSERT INTO order_participants (order_id, category_id, price_rule_id, audience, list_price_cents, paid_cents, snapshot_name)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type InsertOrderParticipantParams struct {
	OrderID        int64
	CategoryID     int64
	PriceRuleID    int64
	Audience       string
	ListPriceCents int64
	PaidCents      int64
	SnapshotName   string
}

func (q *Queries) InsertOrderParticipant(ctx context.Context, arg InsertOrderParticipantParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertOrderParticipant,
		arg.OrderID,
		arg.CategoryID,
		arg.PriceRuleID,
		arg.Audience,
		arg.ListPriceCents,
		arg.PaidCents,
		arg.SnapshotName,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertRegOrder = `-- name: InsertRegOrder :one
INSERT INTO reg_orders (
  order_no, event_id, buyer_user_id, buyer_name, buyer_phone_e164, buyer_email,
  status, reservation_state, list_amount_cents, discount_cents, ident_offset_cents, amount_cents,
  currency, coupon_id, payment_account_id, deadline_at, source
) VALUES (
  $1, $2, $3, $4, $5, $6,
  'PENDING_PAYMENT', 'RESERVED', $7, $8, $9, $10,
  'USD', $11, $12, $13, 'TELEGRAM'
)
RETURNING id
`

type InsertRegOrderParams struct {
	OrderNo          string
	EventID          int64
	BuyerUserID      *int64
	BuyerName        string
	BuyerPhoneE164   string
	BuyerEmail       *string
	ListAmountCents  int64
	DiscountCents    int64
	IdentOffsetCents int16
	AmountCents      int64
	CouponID         *int64
	PaymentAccountID *int64
	DeadlineAt       *time.Time
}

func (q *Queries) InsertRegOrder(ctx context.Context, arg InsertRegOrderParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertRegOrder,
		arg.OrderNo,
		arg.EventID,
		arg.BuyerUserID,
		arg.BuyerName,
		arg.BuyerPhoneE164,
		arg.BuyerEmail,
		arg.ListAmountCents,
		arg.DiscountCents,
		arg.IdentOffsetCents,
		arg.AmountCents,
		arg.CouponID,
		arg.PaymentAccountID,
		arg.DeadlineAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertRegistration = `-- name: InsertRegistration :one
INSERT INTO registrations (
  reg_no, order_participant_id, event_id, category_id, status, ticket_code, user_id,
  full_name, gender, birth_date, nationality, id_type, id_no_enc, id_no_hash,
  phone_e164, email, emergency_name, emergency_phone, tshirt_size
) VALUES (
  $1, $2, $3, $4, 'PENDING', $5, $6,
  $7, $8, $9, $10, $11, $12, $13,
  $14, $15, $16, $17, $18
)
RETURNING id
`

type InsertRegistrationParams struct {
	RegNo              string
	OrderParticipantID int64
	EventID            int64
	CategoryID         int64
	TicketCode         string
	UserID             *int64
	FullName           string
	Gender             string
	BirthDate          time.Time
	Nationality        string
	IDType             *string
	IDNoEnc            []byte
	IDNoHash           []byte
	PhoneE164          *string
	Email              *string
	EmergencyName      *string
	EmergencyPhone     *string
	TshirtSize         *string
}

func (q *Queries) InsertRegistration(ctx context.Context, arg InsertRegistrationParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertRegistration,
		arg.RegNo,
		arg.OrderParticipantID,
		arg.EventID,
		arg.CategoryID,
		arg.TicketCode,
		arg.UserID,
		arg.FullName,
		arg.Gender,
		arg.BirthDate,
		arg.Nationality,
		arg.IDType,
		arg.IDNoEnc,
		arg.IDNoHash,
		arg.PhoneE164,
		arg.Email,
		arg.EmergencyName,
		arg.EmergencyPhone,
		arg.TshirtSize,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listDueOrderIDsForExpiry = `-- name: ListDueOrderIDsForExpiry :many
SELECT id
FROM reg_orders
WHERE status IN ('PENDING_PAYMENT', 'PROOF_REJECTED')
  AND deadline_at <= $1::timestamptz
ORDER BY deadline_at, id
LIMIT $2::int
FOR UPDATE SKIP LOCKED
`

type ListDueOrderIDsForExpiryParams struct {
	AsOf       time.Time
	BatchLimit int32
}

// 只锁订单行（SKIP LOCKED 跳过上传凭证 / 审核事务正持有的订单），按截止时间先后取一批。
func (q *Queries) ListDueOrderIDsForExpiry(ctx context.Context, arg ListDueOrderIDsForExpiryParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, listDueOrderIDsForExpiry, arg.AsOf, arg.BatchLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFreeSignupsForUser = `-- name: ListFreeSignupsForUser :many
SELECT fs.signup_no, fs.full_name, fs.status, fs.created_at,
       e.slug AS event_slug, e.name AS event_name, e.race_date, ec.name AS category_name
FROM free_signups fs
JOIN events e ON e.id = fs.event_id
JOIN event_categories ec ON ec.id = fs.category_id
WHERE fs.user_id = $1::bigint
ORDER BY fs.created_at DESC, fs.id DESC
LIMIT 100
`

type ListFreeSignupsForUserRow struct {
	SignupNo     string
	FullName     string
	Status       string
	CreatedAt    time.Time
	EventSlug    string
	EventName    []byte
	RaceDate     time.Time
	CategoryName []byte
}

func (q *Queries) ListFreeSignupsForUser(ctx context.Context, userID int64) ([]ListFreeSignupsForUserRow, error) {
	rows, err := q.db.Query(ctx, listFreeSignupsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFreeSignupsForUserRow
	for rows.Next() {
		var i ListFreeSignupsForUserRow
		if err := rows.Scan(
			&i.SignupNo,
			&i.FullName,
			&i.Status,
			&i.CreatedAt,
			&i.EventSlug,
			&i.EventName,
			&i.RaceDate,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderParticipantDetails = `-- name: ListOrderParticipantDetails :many
SELECT r.id AS registration_id, r.reg_no, op.category_id, ec.name AS category_name, r.full_name,
       op.price_rule_id, op.list_price_cents, op.paid_cents, r.status AS registration_status, r.ticket_code
FROM order_participants op
JOIN registrations r ON r.order_participant_id = op.id
JOIN event_categories ec ON ec.id = op.category_id
WHERE op.order_id = $1
ORDER BY op.id
`

type ListOrderParticipantDetailsRow struct {
	RegistrationID     int64
	RegNo              string
	CategoryID         int64
	CategoryName       []byte
	FullName           string
	PriceRuleID        int64
	ListPriceCents     int64
	PaidCents          int64
	RegistrationStatus string
	TicketCode         string
}

func (q *Queries) ListOrderParticipantDetails(ctx context.Context, orderID int64) ([]ListOrderParticipantDetailsRow, error) {
	rows, err := q.db.Query(ctx, listOrderParticipantDetails, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrderParticipantDetailsRow
	for rows.Next() {
		var i ListOrderParticipantDetailsRow
		if err := rows.Scan(
			&i.RegistrationID,
			&i.RegNo,
			&i.CategoryID,
			&i.CategoryName,
			&i.FullName,
			&i.PriceRuleID,
			&i.ListPriceCents,
			&i.PaidCents,
			&i.RegistrationStatus,
			&i.TicketCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersDueForReminder = `-- name: ListOrdersDueForReminder :many
SELECT o.id, o.order_no, o.buyer_user_id, o.deadline_at, e.timezone AS event_timezone
FROM reg_orders o
JOIN events e ON e.id = o.event_id
JOIN users u ON u.id = o.buyer_user_id
WHERE o.status IN ('PENDING_PAYMENT', 'PROOF_REJECTED')
  AND o.deadline_at > $1::timestamptz
  AND o.deadline_at <= $2::timestamptz
  AND u.telegram_user_id IS NOT NULL
  AND NOT EXISTS (
    SELECT 1 FROM notification_logs n
    WHERE n.dedupe_key = 'reminder:' || o.id || ':' || floor(extract(epoch FROM o.deadline_at))::bigint
  )
ORDER BY o.deadline_at, o.id
`

type ListOrdersDueForReminderParams struct {
	AsOf  time.Time
	Until time.Time
}

type ListOrdersDueForReminderRow struct {
	ID            int64
	OrderNo       string
	BuyerUserID   *int64
	DeadlineAt    *time.Time
	EventTimezone string
}

func (q *Queries) ListOrdersDueForReminder(ctx context.Context, arg ListOrdersDueForReminderParams) ([]ListOrdersDueForReminderRow, error) {
	rows, err := q.db.Query(ctx, listOrdersDueForReminder, arg.AsOf, arg.Until)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrdersDueForReminderRow
	for rows.Next() {
		var i ListOrdersDueForReminderRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderNo,
			&i.BuyerUserID,
			&i.DeadlineAt,
			&i.EventTimezone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersForBuyer = `-- name: ListOrdersForBuyer :many
SELECT o.id, o.order_no, o.event_id, o.buyer_user_id, o.status, o.reservation_state,
       o.list_amount_cents, o.discount_cents, o.ident_offset_cents, o.amount_cents, o.currency,
       o.payment_account_id, o.deadline_at, o.paid_at, o.created_at,
       e.slug AS event_slug, e.name AS event_name,
       (SELECT count(*) FROM order_participants op WHERE op.order_id = o.id) AS participant_count
FROM reg_orders o
JOIN events e ON e.id = o.event_id
WHERE o.buyer_user_id = $1::bigint
ORDER BY o.created_at DESC, o.id DESC
LIMIT 100
`

type ListOrdersForBuyerRow struct {
	ID               int64
	OrderNo          string
	EventID          int64
	BuyerUserID      *int64
	Status           string
	ReservationState string
	ListAmountCents  int64
	DiscountCents    int64
	IdentOffsetCents int16
	AmountCents      int64
	Currency         string
	PaymentAccountID *int64
	DeadlineAt       *time.Time
	PaidAt           *time.Time
	CreatedAt        time.Time
	EventSlug        string
	EventName        []byte
	ParticipantCount int64
}

func (q *Queries) ListOrdersForBuyer(ctx context.Context, buyerUserID int64) ([]ListOrdersForBuyerRow, error) {
	rows, err := q.db.Query(ctx, listOrdersForBuyer, buyerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrdersForBuyerRow
	for rows.Next() {
		var i ListOrdersForBuyerRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderNo,
			&i.EventID,
			&i.BuyerUserID,
			&i.Status,
			&i.ReservationState,
			&i.ListAmountCents,
			&i.DiscountCents,
			&i.IdentOffsetCents,
			&i.AmountCents,
			&i.Currency,
			&i.PaymentAccountID,
			&i.DeadlineAt,
			&i.PaidAt,
			&i.CreatedAt,
			&i.EventSlug,
			&i.EventName,
			&i.ParticipantCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRegisteredIDNoHashes = `-- name: ListRegisteredIDNoHashes :many
SELECT id_no_hash
FROM registrations
WHERE event_id = $1::bigint
  AND status IN ('PENDING', 'CONFIRMED')
  AND id_no_hash = ANY($2::bytea[])
`

type ListRegisteredIDNoHashesParams struct {
	EventID int64
	Hashes  [][]byte
}

func (q *Queries) ListRegisteredIDNoHashes(ctx context.Context, arg ListRegisteredIDNoHashesParams) ([][]byte, error) {
	rows, err := q.db.Query(ctx, listRegisteredIDNoHashes, arg.EventID, arg.Hashes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items [][]byte
	for rows.Next() {
		var id_no_hash []byte
		if err := rows.Scan(&id_no_hash); err != nil {
			return nil, err
		}
		items = append(items, id_no_hash)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockEventForOrder = `-- name: LockEventForOrder :one
SELECT id, slug, event_type, status, registration_open, registration_opens_at, registration_closes_at, race_date
FROM events
WHERE slug = $1
FOR SHARE
`

type LockEventForOrderRow struct {
	ID                   int64
	Slug                 string
	EventType            string
	Status               string
	RegistrationOpen     bool
	RegistrationOpensAt  *time.Time
	RegistrationClosesAt *time.Time
	RaceDate             time.Time
}

func (q *Queries) LockEventForOrder(ctx context.Context, slug string) (LockEventForOrderRow, error) {
	row := q.db.QueryRow(ctx, lockEventForOrder, slug)
	var i LockEventForOrderRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.EventType,
		&i.Status,
		&i.RegistrationOpen,
		&i.RegistrationOpensAt,
		&i.RegistrationClosesAt,
		&i.RaceDate,
	)
	return i, err
}

const lockIDNoHash = `-- name: LockIDNoHash :exec
SELECT pg_advisory_xact_lock(hashtextextended(format('%s:%s', $1::bigint, encode($2::bytea, 'hex')), 7302))
`

type LockIDNoHashParams struct {
	EventID  int64
	IDNoHash []byte
}

// 键为 hashtextextended('<eventId>:<hex(hash)>', 7302)。
func (q *Queries) LockIDNoHash(ctx context.Context, arg LockIDNoHashParams) error {
	_, err := q.db.Exec(ctx, lockIDNoHash, arg.EventID, arg.IDNoHash)
	return err
}

const lockOrderForBuyer = `-- name: LockOrderForBuyer :one
SELECT id, event_id, status
FROM reg_orders
WHERE order_no = $1 AND buyer_user_id = $2::bigint
FOR UPDATE
`

type LockOrderForBuyerParams struct {
	OrderNo     string
	BuyerUserID int64
}

type LockOrderForBuyerRow struct {
	ID      int64
	EventID int64
	Status  string
}

func (q *Queries) LockOrderForBuyer(ctx context.Context, arg LockOrderForBuyerParams) (LockOrderForBuyerRow, error) {
	row := q.db.QueryRow(ctx, lockOrderForBuyer, arg.OrderNo, arg.BuyerUserID)
	var i LockOrderForBuyerRow
	err := row.Scan(&i.ID, &i.EventID, &i.Status)
	return i, err
}

const lockRegOrderByID = `-- name: LockRegOrderByID :one
SELECT id, order_no, event_id, buyer_user_id, buyer_name, buyer_phone_e164, buyer_email, status, reservation_state, reservation_release_kind, list_amount_cents, discount_cents, ident_offset_cents, amount_cents, currency, coupon_id, payment_account_id, deadline_at, paid_at, expired_at, cancelled_at, cancel_reason, source, archived, version, created_at, updated_at FROM reg_orders
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockRegOrderByID(ctx context.Context, id int64) (RegOrder, error) {
	row := q.db.QueryRow(ctx, lockRegOrderByID, id)
	var i RegOrder
	err := row.Scan(
		&i.ID,
		&i.OrderNo,
		&i.EventID,
		&i.BuyerUserID,
		&i.BuyerName,
		&i.BuyerPhoneE164,
		&i.BuyerEmail,
		&i.Status,
		&i.ReservationState,
		&i.ReservationReleaseKind,
		&i.ListAmountCents,
		&i.DiscountCents,
		&i.IdentOffsetCents,
		&i.AmountCents,
		&i.Currency,
		&i.CouponID,
		&i.PaymentAccountID,
		&i.DeadlineAt,
		&i.PaidAt,
		&i.ExpiredAt,
		&i.CancelledAt,
		&i.CancelReason,
		&i.Source,
		&i.Archived,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockRegOrderByNo = `-- name: LockRegOrderByNo :one
SELECT id, order_no, event_id, buyer_user_id, buyer_name, buyer_phone_e164, buyer_email, status, reservation_state, reservation_release_kind, list_amount_cents, discount_cents, ident_offset_cents, amount_cents, currency, coupon_id, payment_account_id, deadline_at, paid_at, expired_at, cancelled_at, cancel_reason, source, archived, version, created_at, updated_at FROM reg_orders
WHERE order_no = $1
FOR UPDATE
`

func (q *Queries) LockRegOrderByNo(ctx context.Context, orderNo string) (RegOrder, error) {
	row := q.db.QueryRow(ctx, lockRegOrderByNo, orderNo)
	var i RegOrder
	err := row.Scan(
		&i.ID,
		&i.OrderNo,
		&i.EventID,
		&i.BuyerUserID,
		&i.BuyerName,
		&i.BuyerPhoneE164,
		&i.BuyerEmail,
		&i.Status,
		&i.ReservationState,
		&i.ReservationReleaseKind,
		&i.ListAmountCents,
		&i.DiscountCents,
		&i.IdentOffsetCents,
		&i.AmountCents,
		&i.Currency,
		&i.CouponID,
		&i.PaymentAccountID,
		&i.DeadlineAt,
		&i.PaidAt,
		&i.ExpiredAt,
		&i.CancelledAt,
		&i.CancelReason,
		&i.Source,
		&i.Archived,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markOrderPaid = `-- name: MarkOrderPaid :execrows
UPDATE reg_orders
SET status = 'PAID',
    paid_at = $1::timestamptz,
    deadline_at = NULL,
    reservation_state = 'CONSUMED',
    version = version + 1
WHERE id = $2
  AND reservation_state = 'RESERVED'
  AND (status = 'PROOF_SUBMITTED' OR (status = 'PENDING_PAYMENT' AND amount_cents = 0))
`

type MarkOrderPaidParams struct {
	PaidAt time.Time
	ID     int64
}

// 订单条件更新：只有预留仍为 RESERVED 的订单能转为 PAID/CONSUMED，保证 pricing.Consume 每单只调用一次。
func (q *Queries) MarkOrderPaid(ctx context.Context, arg MarkOrderPaidParams) (int64, error) {
	result, err := q.db.Exec(ctx, markOrderPaid, arg.PaidAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeExpiredIdempotencyKeys = `-- name: PurgeExpiredIdempotencyKeys :execrows
DELETE FROM idempotency_keys k
USING (
  SELECT scope, subject, key
  FROM idempotency_keys
  WHERE expires_at < $1::timestamptz
  LIMIT $2::int
) d
WHERE k.scope = d.scope AND k.subject = d.subject AND k.key = d.key
  AND k.expires_at < $1::timestamptz
`

type PurgeExpiredIdempotencyKeysParams struct {
	Now        time.Time
	BatchLimit int32
}

// 每次至多删除 batch_limit 条已过期的幂等键。外层再判一次 expires_at：
// READ COMMITTED 下若同名键刚被 ClaimIdempotencyKey 续期，重新检查最新行版本后不会误删。
func (q *Queries) PurgeExpiredIdempotencyKeys(ctx context.Context, arg PurgeExpiredIdempotencyKeysParams) (int64, error) {
	result, err := q.db.Exec(ctx, purgeExpiredIdempotencyKeys, arg.Now, arg.BatchLimit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const releaseOrderCancelled = `-- name: ReleaseOrderCancelled :execrows
UPDATE reg_orders
SET status = 'CANCELLED',
    reservation_state = 'RELEASED',
    reservation_release_kind = 'ORDER_CANCELLED',
    cancelled_at = $1::timestamptz,
    deadline_at = NULL,
    version = version + 1
WHERE id = $2
  AND reservation_state = 'RESERVED'
  AND status = 'PENDING_PAYMENT'
`

type ReleaseOrderCancelledParams struct {
	At time.Time
	ID int64
}

func (q *Queries) ReleaseOrderCancelled(ctx context.Context, arg ReleaseOrderCancelledParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseOrderCancelled, arg.At, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const releaseOrderExpired = `-- name: ReleaseOrderExpired :execrows
UPDATE reg_orders
SET status = 'EXPIRED',
    reservation_state = 'RELEASED',
    reservation_release_kind = 'ORDER_EXPIRED',
    expired_at = $1::timestamptz,
    deadline_at = NULL,
    version = version + 1
WHERE id = $2
  AND reservation_state = 'RESERVED'
  AND status IN ('PENDING_PAYMENT', 'PROOF_REJECTED')
`

type ReleaseOrderExpiredParams struct {
	At time.Time
	ID int64
}

func (q *Queries) ReleaseOrderExpired(ctx context.Context, arg ReleaseOrderExpiredParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseOrderExpired, arg.At, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const saveIdempotencyResponse = `-- name: SaveIdempotencyResponse :exec
UPDATE idempotency_keys
SET response_code = $1::int, response_body = $2::jsonb
WHERE scope = $3 AND subject = $4 AND key = $5
`

type SaveIdempotencyResponseParams struct {
	ResponseCode int32
	ResponseBody []byte
	Scope        string
	Subject      string
	Key          string
}

func (q *Queries) SaveIdempotencyResponse(ctx context.Context, arg SaveIdempotencyResponseParams) error {
	_, err := q.db.Exec(ctx, saveIdempotencyResponse,
		arg.ResponseCode,
		arg.ResponseBody,
		arg.Scope,
		arg.Subject,
		arg.Key,
	)
	return err
}

const selectRegistrationPaymentAccount = `-- name: SelectRegistrationPaymentAccount :one
SELECT id
FROM payment_accounts
WHERE active
  AND currency = 'USD'
  AND scope IN ('REGISTRATION', 'ALL')
  AND (event_id = $1::bigint OR event_id IS NULL)
ORDER BY (event_id IS NULL), id
LIMIT 1
`

func (q *Queries) SelectRegistrationPaymentAccount(ctx context.Context, eventID int64) (int64, error) {
	row := q.db.QueryRow(ctx, selectRegistrationPaymentAccount, eventID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const setOrderProofRejected = `-- name: SetOrderProofRejected :execrows
UPDATE reg_orders
SET status = 'PROOF_REJECTED',
    deadline_at = $1::timestamptz,
    version = version + 1
WHERE id = $2
  AND reservation_state = 'RESERVED'
  AND status = 'PROOF_SUBMITTED'
`

type SetOrderProofRejectedParams struct {
	DeadlineAt time.Time
	ID         int64
}

// 条件更新：只有预留仍为 RESERVED、处于审核中的订单能被驳回并进入重传期。
func (q *Queries) SetOrderProofRejected(ctx context.Context, arg SetOrderProofRejectedParams) (int64, error) {
	result, err := q.db.Exec(ctx, setOrderProofRejected, arg.DeadlineAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setOrderProofSubmitted = `-- name: SetOrderProofSubmitted :execrows
UPDATE reg_orders
SET status = 'PROOF_SUBMITTED',
    deadline_at = NULL,
    version = version + 1
WHERE id = $1
  AND reservation_state = 'RESERVED'
  AND status IN ('PENDING_PAYMENT', 'PROOF_REJECTED')
`

func (q *Queries) SetOrderProofSubmitted(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, setOrderProofSubmitted, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
