// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: registration.sql

package store

import (
	"context"
	"time"
)

const claimIdempotencyKey = `-- name: ClaimIdempotencyKey :one
INSERT INTO idempotency_keys (key, scope, subject, request_hash, created_at, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (scope, subject, key) DO UPDATE
SET request_hash = EXCLUDED.request_hash,
    response_code = NULL,
    response_body = NULL,
    created_at = EXCLUDED.created_at,
    expires_at = EXCLUDED.expires_at
WHERE idempotency_keys.expires_at <= EXCLUDED.created_at
RETURNING key
`

type ClaimIdempotencyKeyParams struct {
	Key         string
	Scope       string
	Subject     string
	RequestHash []byte
	Now         time.Time
	ExpiresAt   time.Time
}

// 新键直接插入；已过期的同名键被覆盖；未过期的同名键不返回行（并等待持有它的事务结束）。
func (q *Queries) ClaimIdempotencyKey(ctx context.Context, arg ClaimIdempotencyKeyParams) (string, error) {
	row := q.db.QueryRow(ctx, claimIdempotencyKey,
		arg.Key,
		arg.Scope,
		arg.Subject,
		arg.RequestHash,
		arg.Now,
		arg.ExpiresAt,
	)
	var key string
	err := row.Scan(&key)
	return key, err
}

const confirmOrderRegistrations = `-- name: ConfirmOrderRegistrations :execrows
UPDATE registrations r
SET status = 'CONFIRMED', confirmed_at = $1::timestamptz, version = r.version + 1
FROM order_participants op
WHERE op.id = r.order_participant_id
  AND op.order_id = $2::bigint
  AND r.status = 'PENDING'
`

type ConfirmOrderRegistrationsParams struct {
	ConfirmedAt time.Time
	OrderID     int64
}

func (q *Queries) ConfirmOrderRegistrations(ctx context.Context, arg ConfirmOrderRegistrationsParams) (int64, error) {
	result, err := q.db.Exec(ctx, confirmOrderRegistrations, arg.ConfirmedAt, arg.OrderID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getEventForQuote = `-- name: GetEventForQuote :one
SELECT id, event_type, status, race_date
FROM events
WHERE slug = $1
`

type GetEventForQuoteRow struct {
	ID        int64
	EventType string
	Status    string
	RaceDate  time.Time
}

func (q *Queries) GetEventForQuote(ctx context.Context, slug string) (GetEventForQuoteRow, error) {
	row := q.db.QueryRow(ctx, getEventForQuote, slug)
	var i GetEventForQuoteRow
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.Status,
		&i.RaceDate,
	)
	return i, err
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT request_hash, response_code, response_body
FROM idempotency_keys
WHERE scope = $1 AND subject = $2 AND key = $3
`

type GetIdempotencyKeyParams struct {
	Scope   string
	Subject string
	Key     string
}

type GetIdempotencyKeyRow struct {
	RequestHash  []byte
	ResponseCode *int32
	ResponseBody []byte
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (GetIdempotencyKeyRow, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, arg.Scope, arg.Subject, arg.Key)
	var i GetIdempotencyKeyRow
	err := row.Scan(&i.RequestHash, &i.ResponseCode, &i.ResponseBody)
	return i, err
}

const getLastRejectedProof = `-- name: GetLastRejectedProof :one
SELECT reject_code, reject_reason, reviewed_at
FROM payment_proofs
WHERE reg_order_id = $1::bigint AND status = 'REJECTED'
ORDER BY reviewed_at DESC, id DESC
LIMIT 1
`

type GetLastRejectedProofRow struct {
	RejectCode   *string
	RejectReason *string
	ReviewedAt   *time.Time
}

func (q *Queries) GetLastRejectedProof(ctx context.Context, regOrderID int64) (GetLastRejectedProofRow, error) {
	row := q.db.QueryRow(ctx, getLastRejectedProof, regOrderID)
	var i GetLastRejectedProofRow
	err := row.Scan(&i.RejectCode, &i.RejectReason, &i.ReviewedAt)
	return i, err
}

const getOrderDetailByID = `-- name: GetOrderDetailByID :one
SELECT o.id, o.order_no, o.event_id, o.buyer_user_id, o.status, o.reservation_state,
       o.list_amount_cents, o.discount_cents, o.ident_offset_cents, o.amount_cents, o.currency,
       o.payment_account_id, o.deadline_at, o.paid_at, o.created_at,
       e.slug AS event_slug, e.name AS event_name, e.timezone AS event_timezone
FROM reg_orders o
JOIN events e ON e.id = o.event_id
WHERE o.id = $1
`

type GetOrderDetailByIDRow struct {
	ID               int64
	OrderNo          string
	EventID          int64
	BuyerUserID      *int64
	Status           string
	ReservationState string
	ListAmountCents  int64
	DiscountCents    int64
	IdentOffsetCents int16
	AmountCents      int64
	Currency         string
	PaymentAccountID *int64
	DeadlineAt       *time.Time
	PaidAt           *time.Time
	CreatedAt        time.Time
	EventSlug        string
	EventName        []byte
	EventTimezone    string
}

func (q *Queries) GetOrderDetailByID(ctx context.Context, id int64) (GetOrderDetailByIDRow, error) {
	row := q.db.QueryRow(ctx, getOrderDetailByID, id)
	var i GetOrderDetailByIDRow
	err := row.Scan(
		&i.ID,
		&i.OrderNo,
		&i.EventID,
		&i.BuyerUserID,
		&i.Status,
		&i.ReservationState,
		&i.ListAmountCents,
		&i.DiscountCents,
		&i.IdentOffsetCents,
		&i.AmountCents,
		&i.Currency,
		&i.PaymentAccountID,
		&i.DeadlineAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.EventSlug,
		&i.EventName,
		&i.EventTimezone,
	)
	return i, err
}

const getOrderPaymentAccount = `-- name: GetOrderPaymentAccount :one
SELECT id, name, provider, account_name, account_no_masked, qr_file_id
FROM payment_accounts
WHERE id = $1
`

type GetOrderPaymentAccountRow struct {
	ID              int64
	Name            string
	Provider        string
	AccountName     string
	AccountNoMasked string
	QrFileID        int64
}

func (q *Queries) GetOrderPaymentAccount(ctx context.Context, id int64) (GetOrderPaymentAccountRow, error) {
	row := q.db.QueryRow(ctx, getOrderPaymentAccount, id)
	var i GetOrderPaymentAccountRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.AccountName,
		&i.AccountNoMasked,
		&i.QrFileID,
	)
	return i, err
}

const insertOrderParticipant = `-- name: InsertOrderParticipant :one
INSERT INTO order_participants (order_id, category_id, price_rule_id, audience, list_price_cents, paid_cents, snapshot_name)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type InsertOrderParticipantParams struct {
	OrderID        int64
	CategoryID     int64
	PriceRuleID    int64
	Audience       string
	ListPriceCents int64
	PaidCents      int64
	SnapshotName   string
}

func (q *Queries) InsertOrderParticipant(ctx context.Context, arg InsertOrderParticipantParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertOrderParticipant,
		arg.OrderID,
		arg.CategoryID,
		arg.PriceRuleID,
		arg.Audience,
		arg.ListPriceCents,
		arg.PaidCents,
		arg.SnapshotName,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertRegOrder = `-- name: InsertRegOrder :one
INSERT INTO reg_orders (
  order_no, event_id, buyer_user_id, buyer_name, buyer_phone_e164, buyer_email,
  status, reservation_state, list_amount_cents, discount_cents, ident_offset_cents, amount_cents,
  currency, coupon_id, payment_account_id, deadline_at, source
) VALUES (
  $1, $2, $3, $4, $5, $6,
  'PENDING_PAYMENT', 'RESERVED', $7, $8, $9, $10,
  'USD', $11, $12, $13, 'TELEGRAM'
)
RETURNING id
`

type InsertRegOrderParams struct {
	OrderNo          string
	EventID          int64
	BuyerUserID      *int64
	BuyerName        string
	BuyerPhoneE164   string
	BuyerEmail       *string
	ListAmountCents  int64
	DiscountCents    int64
	IdentOffsetCents int16
	AmountCents      int64
	CouponID         *int64
	PaymentAccountID *int64
	DeadlineAt       *time.Time
}

func (q *Queries) InsertRegOrder(ctx context.Context, arg InsertRegOrderParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertRegOrder,
		arg.OrderNo,
		arg.EventID,
		arg.BuyerUserID,
		arg.BuyerName,
		arg.BuyerPhoneE164,
		arg.BuyerEmail,
		arg.ListAmountCents,
		arg.DiscountCents,
		arg.IdentOffsetCents,
		arg.AmountCents,
		arg.CouponID,
		arg.PaymentAccountID,
		arg.DeadlineAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertRegistration = `-- name: InsertRegistration :one
INSERT INTO registrations (
  reg_no, order_participant_id, event_id, category_id, status, ticket_code, user_id,
  full_name, gender, birth_date, nationality, id_type, id_no_enc, id_no_hash,
  phone_e164, email, emergency_name, emergency_phone, tshirt_size
) VALUES (
  $1, $2, $3, $4, 'PENDING', $5, $6,
  $7, $8, $9, $10, $11, $12, $13,
  $14, $15, $16, $17, $18
)
RETURNING id
`

type InsertRegistrationParams struct {
	RegNo              string
	OrderParticipantID int64
	EventID            int64
	CategoryID         int64
	TicketCode         string
	UserID             *int64
	FullName           string
	Gender             string
	BirthDate          time.Time
	Nationality        string
	IDType             *string
	IDNoEnc            []byte
	IDNoHash           []byte
	PhoneE164          *string
	Email              *string
	EmergencyName      *string
	EmergencyPhone     *string
	TshirtSize         *string
}

func (q *Queries) InsertRegistration(ctx context.Context, arg InsertRegistrationParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertRegistration,
		arg.RegNo,
		arg.OrderParticipantID,
		arg.EventID,
		arg.CategoryID,
		arg.TicketCode,
		arg.UserID,
		arg.FullName,
		arg.Gender,
		arg.BirthDate,
		arg.Nationality,
		arg.IDType,
		arg.IDNoEnc,
		arg.IDNoHash,
		arg.PhoneE164,
		arg.Email,
		arg.EmergencyName,
		arg.EmergencyPhone,
		arg.TshirtSize,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listOrderParticipantDetails = `-- name: ListOrderParticipantDetails :many
SELECT r.id AS registration_id, r.reg_no, op.category_id, ec.name AS category_name, r.full_name,
       op.price_rule_id, op.list_price_cents, op.paid_cents, r.status AS registration_status, r.ticket_code
FROM order_participants op
JOIN registrations r ON r.order_participant_id = op.id
JOIN event_categories ec ON ec.id = op.category_id
WHERE op.order_id = $1
ORDER BY op.id
`

type ListOrderParticipantDetailsRow struct {
	RegistrationID     int64
	RegNo              string
	CategoryID         int64
	CategoryName       []byte
	FullName           string
	PriceRuleID        int64
	ListPriceCents     int64
	PaidCents          int64
	RegistrationStatus string
	TicketCode         string
}

func (q *Queries) ListOrderParticipantDetails(ctx context.Context, orderID int64) ([]ListOrderParticipantDetailsRow, error) {
	rows, err := q.db.Query(ctx, listOrderParticipantDetails, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrderParticipantDetailsRow
	for rows.Next() {
		var i ListOrderParticipantDetailsRow
		if err := rows.Scan(
			&i.RegistrationID,
			&i.RegNo,
			&i.CategoryID,
			&i.CategoryName,
			&i.FullName,
			&i.PriceRuleID,
			&i.ListPriceCents,
			&i.PaidCents,
			&i.RegistrationStatus,
			&i.TicketCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRegisteredIDNoHashes = `-- name: ListRegisteredIDNoHashes :many
SELECT id_no_hash
FROM registrations
WHERE event_id = $1::bigint
  AND status IN ('PENDING', 'CONFIRMED')
  AND id_no_hash = ANY($2::bytea[])
`

type ListRegisteredIDNoHashesParams struct {
	EventID int64
	Hashes  [][]byte
}

func (q *Queries) ListRegisteredIDNoHashes(ctx context.Context, arg ListRegisteredIDNoHashesParams) ([][]byte, error) {
	rows, err := q.db.Query(ctx, listRegisteredIDNoHashes, arg.EventID, arg.Hashes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items [][]byte
	for rows.Next() {
		var id_no_hash []byte
		if err := rows.Scan(&id_no_hash); err != nil {
			return nil, err
		}
		items = append(items, id_no_hash)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockEventForOrder = `-- name: LockEventForOrder :one
SELECT id, slug, event_type, status, registration_open, registration_opens_at, registration_closes_at, race_date
FROM events
WHERE slug = $1
FOR SHARE
`

type LockEventForOrderRow struct {
	ID                   int64
	Slug                 string
	EventType            string
	Status               string
	RegistrationOpen     bool
	RegistrationOpensAt  *time.Time
	RegistrationClosesAt *time.Time
	RaceDate             time.Time
}

func (q *Queries) LockEventForOrder(ctx context.Context, slug string) (LockEventForOrderRow, error) {
	row := q.db.QueryRow(ctx, lockEventForOrder, slug)
	var i LockEventForOrderRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.EventType,
		&i.Status,
		&i.RegistrationOpen,
		&i.RegistrationOpensAt,
		&i.RegistrationClosesAt,
		&i.RaceDate,
	)
	return i, err
}

const lockIDNoHash = `-- name: LockIDNoHash :exec
SELECT pg_advisory_xact_lock(hashtextextended(format('%s:%s', $1::bigint, encode($2::bytea, 'hex')), 7302))
`

type LockIDNoHashParams struct {
	EventID  int64
	IDNoHash []byte
}

// 键为 hashtextextended('<eventId>:<hex(hash)>', 7302)。
func (q *Queries) LockIDNoHash(ctx context.Context, arg LockIDNoHashParams) error {
	_, err := q.db.Exec(ctx, lockIDNoHash, arg.EventID, arg.IDNoHash)
	return err
}

const markOrderPaid = `-- name: MarkOrderPaid :execrows
UPDATE reg_orders
SET status = 'PAID',
    paid_at = $1::timestamptz,
    deadline_at = NULL,
    reservation_state = 'CONSUMED',
    version = version + 1
WHERE id = $2
  AND reservation_state = 'RESERVED'
  AND (status = 'PROOF_SUBMITTED' OR (status = 'PENDING_PAYMENT' AND amount_cents = 0))
`

type MarkOrderPaidParams struct {
	PaidAt time.Time
	ID     int64
}

// 订单条件更新：只有预留仍为 RESERVED 的订单能转为 PAID/CONSUMED，保证 pricing.Consume 每单只调用一次。
func (q *Queries) MarkOrderPaid(ctx context.Context, arg MarkOrderPaidParams) (int64, error) {
	result, err := q.db.Exec(ctx, markOrderPaid, arg.PaidAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const saveIdempotencyResponse = `-- name: SaveIdempotencyResponse :exec
UPDATE idempotency_keys
SET response_code = $1::int, response_body = $2::jsonb
WHERE scope = $3 AND subject = $4 AND key = $5
`

type SaveIdempotencyResponseParams struct {
	ResponseCode int32
	ResponseBody []byte
	Scope        string
	Subject      string
	Key          string
}

func (q *Queries) SaveIdempotencyResponse(ctx context.Context, arg SaveIdempotencyResponseParams) error {
	_, err := q.db.Exec(ctx, saveIdempotencyResponse,
		arg.ResponseCode,
		arg.ResponseBody,
		arg.Scope,
		arg.Subject,
		arg.Key,
	)
	return err
}

const selectRegistrationPaymentAccount = `-- name: SelectRegistrationPaymentAccount :one
SELECT id
FROM payment_accounts
WHERE active
  AND currency = 'USD'
  AND scope IN ('REGISTRATION', 'ALL')
  AND (event_id = $1::bigint OR event_id IS NULL)
ORDER BY (event_id IS NULL), id
LIMIT 1
`

func (q *Queries) SelectRegistrationPaymentAccount(ctx context.Context, eventID int64) (int64, error) {
	row := q.db.QueryRow(ctx, selectRegistrationPaymentAccount, eventID)
	var id int64
	err := row.Scan(&id)
	return id, err
}
