// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: iam.sql

package store

import (
	"context"
	"net/netip"
	"time"
)

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions
WHERE expires_at < $1
   OR revoked_at < $1
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, cutoff time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getStaffByUsername = `-- name: GetStaffByUsername :one
SELECT id, username, full_name, role, password_hash, status
FROM staff
WHERE username = $1
`

type GetStaffByUsernameRow struct {
	ID           int64
	Username     string
	FullName     string
	Role         string
	PasswordHash string
	Status       string
}

func (q *Queries) GetStaffByUsername(ctx context.Context, username string) (GetStaffByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getStaffByUsername, username)
	var i GetStaffByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FullName,
		&i.Role,
		&i.PasswordHash,
		&i.Status,
	)
	return i, err
}

const getStaffSession = `-- name: GetStaffSession :one
SELECT s.id AS session_id,
       s.expires_at,
       s.created_at,
       s.revoked_at,
       st.id AS staff_id,
       st.username,
       st.full_name,
       st.role,
       st.status
FROM sessions s
JOIN staff st ON st.id = s.subject_id
WHERE s.subject_type = 'STAFF'
  AND s.token_hash = $1
`

type GetStaffSessionRow struct {
	SessionID int64
	ExpiresAt time.Time
	CreatedAt time.Time
	RevokedAt *time.Time
	StaffID   int64
	Username  string
	FullName  string
	Role      string
	Status    string
}

func (q *Queries) GetStaffSession(ctx context.Context, tokenHash []byte) (GetStaffSessionRow, error) {
	row := q.db.QueryRow(ctx, getStaffSession, tokenHash)
	var i GetStaffSessionRow
	err := row.Scan(
		&i.SessionID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.StaffID,
		&i.Username,
		&i.FullName,
		&i.Role,
		&i.Status,
	)
	return i, err
}

const insertStaff = `-- name: InsertStaff :one
INSERT INTO staff (username, full_name, role, password_hash)
VALUES ($1, $2, $3, $4)
RETURNING id, username, full_name, role
`

type InsertStaffParams struct {
	Username     string
	FullName     string
	Role         string
	PasswordHash string
}

type InsertStaffRow struct {
	ID       int64
	Username string
	FullName string
	Role     string
}

func (q *Queries) InsertStaff(ctx context.Context, arg InsertStaffParams) (InsertStaffRow, error) {
	row := q.db.QueryRow(ctx, insertStaff,
		arg.Username,
		arg.FullName,
		arg.Role,
		arg.PasswordHash,
	)
	var i InsertStaffRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FullName,
		&i.Role,
	)
	return i, err
}

const insertStaffSession = `-- name: InsertStaffSession :exec
INSERT INTO sessions (subject_type, subject_id, token_hash, expires_at, ip, user_agent, created_at)
VALUES ('STAFF', $1, $2, $3, $4, $5, $6)
`

type InsertStaffSessionParams struct {
	StaffID   int64
	TokenHash []byte
	ExpiresAt time.Time
	Ip        *netip.Addr
	UserAgent *string
	CreatedAt time.Time
}

func (q *Queries) InsertStaffSession(ctx context.Context, arg InsertStaffSessionParams) error {
	_, err := q.db.Exec(ctx, insertStaffSession,
		arg.StaffID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.Ip,
		arg.UserAgent,
		arg.CreatedAt,
	)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions SET revoked_at = $1
WHERE token_hash = $2 AND revoked_at IS NULL
`

type RevokeSessionParams struct {
	RevokedAt *time.Time
	TokenHash []byte
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) error {
	_, err := q.db.Exec(ctx, revokeSession, arg.RevokedAt, arg.TokenHash)
	return err
}

const setStaffLastLogin = `-- name: SetStaffLastLogin :exec
UPDATE staff SET last_login_at = $1 WHERE id = $2
`

type SetStaffLastLoginParams struct {
	LastLoginAt *time.Time
	ID          int64
}

func (q *Queries) SetStaffLastLogin(ctx context.Context, arg SetStaffLastLoginParams) error {
	_, err := q.db.Exec(ctx, setStaffLastLogin, arg.LastLoginAt, arg.ID)
	return err
}

const updateSessionExpiry = `-- name: UpdateSessionExpiry :exec
UPDATE sessions SET expires_at = $1
WHERE id = $2 AND revoked_at IS NULL
`

type UpdateSessionExpiryParams struct {
	ExpiresAt time.Time
	ID        int64
}

func (q *Queries) UpdateSessionExpiry(ctx context.Context, arg UpdateSessionExpiryParams) error {
	_, err := q.db.Exec(ctx, updateSessionExpiry, arg.ExpiresAt, arg.ID)
	return err
}
