// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"net/netip"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID          int64
	OccurredAt  time.Time
	ActorType   string
	ActorID     *int64
	ActorRole   *string
	Action      string
	EntityType  string
	EntityID    int64
	EventID     *int64
	IsFinancial bool
	Summary     string
	BeforeData  []byte
	AfterData   []byte
	RequestID   *string
	Ip          *netip.Addr
	UserAgent   *string
}

type AuthOtp struct {
	ID         int64
	PhoneE164  string
	CodeHash   []byte
	Purpose    string
	Attempts   int16
	ExpiresAt  time.Time
	ConsumedAt *time.Time
	Ip         *netip.Addr
	CreatedAt  time.Time
}

type BankStatementImport struct {
	ID               int64
	PaymentAccountID int64
	PeriodStart      time.Time
	PeriodEnd        time.Time
	FileID           int64
	LineCount        int32
	ImportedBy       int64
	CreatedAt        time.Time
}

type BankStatementLine struct {
	ID               int64
	ImportID         int64
	PaymentAccountID int64
	TxnRef           string
	AmountCents      int64
	Currency         string
	TxnAt            time.Time
	Counterparty     *string
	Memo             *string
	ReceiptID        *int64
}

type BibAssignment struct {
	ID              int64
	EventID         int64
	BibNumber       int32
	RegistrationID  *int64
	Status          string
	AssignMethod    *string
	HolderName      *string
	ImportJobID     *int64
	SupersededByID  *int64
	Note            *string
	CreatedBy       *int64
	CreatedAt       time.Time
	StatusChangedAt time.Time
}

type BibRange struct {
	ID            int64
	EventID       int64
	CategoryID    int64
	RangeFrom     int32
	RangeTo       int32
	ReservedFrom  *int32
	ReservedTo    *int32
	AssignMode    string
	DisplayDigits int16
}

type CategoryPriceRule struct {
	CategoryID  int64
	PriceRuleID int64
}

type CommunityActivity struct {
	ID                int64
	AuthorUserID      int64
	EventID           *int64
	ReviewRequired    bool
	SignatureID       int64
	Title             string
	Tag               string
	StartsAt          time.Time
	Location          string
	MeetPoint         string
	DistanceText      *string
	Capacity          int32
	JoinedCount       int32
	FeeNote           string
	ContactTelegram   *string
	ContactPhone      *string
	ContactVisibility string
	Body              string
	Status            string
	RejectCode        *string
	ReviewedBy        *int64
	ReviewedAt        *time.Time
	Frozen            bool
	FreezeReason      *string
	FrozenBy          *int64
	FrozenAt          *time.Time
	ReportCount       int32
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type CommunityActivityImage struct {
	ActivityID int64
	FileID     int64
	SortOrder  int16
}

type CommunityActivityJoin struct {
	ActivityID int64
	UserID     int64
	Status     string
	JoinedAt   time.Time
	LeftAt     *time.Time
}

type CommunityReport struct {
	ID         int64
	ActivityID int64
	ReporterID int64
	ReasonCode string
	Detail     *string
	Status     string
	HandledBy  *int64
	HandledAt  *time.Time
	CreatedAt  time.Time
}

type ContactViewLog struct {
	ID           int64
	ActivityID   int64
	ViewerUserID int64
	ContactType  string
	ViewerJoined bool
	Ip           *netip.Addr
	ViewedAt     time.Time
}

type Content struct {
	ID                 int64
	Title              []byte
	Summary            []byte
	Body               []byte
	CtaLabel           []byte
	CoverFileID        *int64
	SourceNote         string
	Status             string
	StatusBeforeFreeze *string
	UnpublishReason    *string
	FreezeReason       *string
	RecoveryCondition  *string
	FrozenBy           *int64
	FrozenAt           *time.Time
	RecoverNote        *string
	RecoveredBy        *int64
	RecoveredAt        *time.Time
	PublishedAt        *time.Time
	EditCount          int32
	CreatedBy          int64
	UpdatedBy          *int64
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type Coupon struct {
	ID            int64
	Code          string
	EventID       *int64
	DiscountType  string
	DiscountValue int64
	Quota         int32
	UsedCount     int32
	ReservedCount int32
	MinRunners    *int16
	ValidFrom     *time.Time
	ValidUntil    *time.Time
	Description   []byte
	Status        string
	CreatedBy     *int64
	CreatedAt     time.Time
}

type CouponRedemption struct {
	OrderID       int64
	CouponID      int64
	State         string
	DiscountCents int64
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type DisclaimerSignature struct {
	ID             int64
	Version        string
	Lang           string
	TextSha256     []byte
	UserID         int64
	CheckedItems   []byte
	SignedAt       time.Time
	ClientTimezone *string
	Ip             *netip.Addr
	UserAgent      *string
	Device         *string
}

type DisclaimerVersion struct {
	Version       string
	Lang          string
	EffectiveDate time.Time
	FullText      string
	Items         []byte
	TextSha256    []byte
	CreatedAt     time.Time
}

type Event struct {
	ID                      int64
	Slug                    string
	EventType               string
	OrganizerType           string
	Name                    []byte
	Summary                 []byte
	Description             []byte
	City                    string
	Venue                   *string
	RaceDate                time.Time
	Timezone                string
	CoverFileID             *int64
	Status                  string
	RegistrationOpen        bool
	PublicVisible           bool
	RegistrationOpensAt     *time.Time
	RegistrationClosesAt    *time.Time
	RacePackConfigured      bool
	CommunityReviewRequired bool
	ActivityInfo            []byte
	PublishedAt             *time.Time
	PublishedBy             *int64
	CreatedBy               *int64
	Version                 int32
	CreatedAt               time.Time
	UpdatedAt               time.Time
}

type EventCategory struct {
	ID            int64
	EventID       int64
	Code          string
	Name          []byte
	DistanceM     int32
	Capacity      int32
	UsedCount     int32
	ReservedCount int32
	StartAt       *time.Time
	CutoffAt      *time.Time
	MinAge        int16
	SortOrder     int16
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type EventComment struct {
	ID        int64
	EventID   int64
	UserID    *int64
	StaffID   *int64
	Body      string
	LikeCount int32
	Status    string
	CreatedAt time.Time
}

type EventSponsor struct {
	EventID        int64
	SponsorID      int64
	RoleLabel      []byte
	PhotoWatermark bool
	FreePhotoClaim bool
	SortOrder      int16
}

type File struct {
	ID             int64
	StorageKey     string
	Visibility     string
	Purpose        string
	MimeType       string
	SizeBytes      int64
	Sha256         []byte
	Phash          *int64
	Width          *int32
	Height         *int32
	UploadedByType string
	UploadedByID   *int64
	CreatedAt      time.Time
}

type FreeSignup struct {
	ID             int64
	SignupNo       string
	EventID        int64
	CategoryID     int64
	UserID         *int64
	FullName       string
	PhoneE164      string
	Gender         *string
	BirthDate      pgtype.Date
	EmergencyName  *string
	EmergencyPhone *string
	Status         string
	CancelSource   *string
	CancelledAt    *time.Time
	CheckedInAt    *time.Time
	CheckedInBy    *int64
	Source         string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type IdempotencyKey struct {
	Key          string
	Scope        string
	Subject      string
	RequestHash  []byte
	ResponseCode *int32
	ResponseBody []byte
	CreatedAt    time.Time
	ExpiresAt    time.Time
}

type ImportJob struct {
	ID         int64
	JobType    string
	EventID    *int64
	FileID     *int64
	Status     string
	TotalRows  *int32
	OkRows     *int32
	ErrorRows  *int32
	Errors     []byte
	CreatedBy  *int64
	CreatedAt  time.Time
	FinishedAt *time.Time
}

type InventoryAdjustment struct {
	ID             int64
	SkuID          int64
	Delta          int32
	Reason         string
	BeforeOnHand   int32
	AfterOnHand    int32
	SourceOrderID  *int64
	SourceRefundID *int64
	Note           *string
	CreatedBy      *int64
	CreatedAt      time.Time
}

type MerchOrder struct {
	ID                     int64
	OrderNo                string
	EventID                *int64
	BuyerUserID            *int64
	BuyerName              string
	BuyerPhoneE164         string
	Status                 string
	RefundState            string
	Fulfillment            string
	ListAmountCents        int64
	IdentOffsetCents       int16
	AmountCents            int64
	Currency               string
	PaymentAccountID       *int64
	DeadlineAt             *time.Time
	PaidAt                 *time.Time
	ExpiredAt              *time.Time
	CancelledAt            *time.Time
	CancelSource           *string
	CancelReason           *string
	ReservationReleased    bool
	ReservationReleaseKind *string
	StockDeducted          bool
	HandoffAt              *time.Time
	HandoffLocation        *string
	HandoffBy              *int64
	HandoffRecipient       *string
	Source                 string
	Version                int32
	CreatedAt              time.Time
	UpdatedAt              time.Time
}

type MerchOrderItem struct {
	ID             int64
	OrderID        int64
	SkuID          int64
	ProductID      int64
	ProductName    string
	Variant        string
	Size           string
	UnitPriceCents int64
	Qty            int32
	AmountCents    int64
}

type MerchProduct struct {
	ID            int64
	EventID       *int64
	Name          []byte
	Description   []byte
	CoverFileID   *int64
	Status        string
	OffSaleReason *string
	CreatedBy     *int64
	UpdatedBy     *int64
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type MerchRefund struct {
	ID                int64
	RefundNo          string
	OrderID           int64
	Scope             string
	Origin            string
	SourceExceptionID *int64
	RequiredCents     int64
	SettledCents      *int64
	Currency          string
	Status            string
	Reason            string
	InitiatedByRole   string
	RequestedBy       int64
	ApprovedBy        *int64
	ApprovedAt        *time.Time
	SettledBy         *int64
	SettledAt         *time.Time
	PayoutTxnRef      *string
	PayoutProofFileID *int64
	RejectedBy        *int64
	RejectedAt        *time.Time
	RejectReason      *string
	UserConfirmation  *string
	ReturnReceivedAt  *time.Time
	ReturnReceivedBy  *int64
	ReturnNote        *string
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type MerchSku struct {
	ID         int64
	ProductID  int64
	Variant    string
	Size       string
	PriceCents int64
	Currency   string
	OnHand     int32
	Reserved   int32
	Saleable   bool
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type NotificationLog struct {
	ID         int64
	Channel    string
	Recipient  string
	Template   string
	Locale     string
	EntityType *string
	EntityID   *int64
	DedupeKey  string
	Status     string
	Attempts   int16
	LastError  *string
	SentAt     *time.Time
	CreatedAt  time.Time
}

type OpsAlert struct {
	ID         int64
	AlertType  string
	Severity   string
	EventID    *int64
	EntityType *string
	EntityID   *int64
	Message    string
	Status     string
	AckedBy    *int64
	AckedAt    *time.Time
	CreatedAt  time.Time
}

type OrderParticipant struct {
	ID             int64
	OrderID        int64
	CategoryID     int64
	PriceRuleID    int64
	Audience       string
	ListPriceCents int64
	PaidCents      int64
	SnapshotName   string
	OpStatus       string
	CreatedAt      time.Time
}

type PaymentAccount struct {
	ID              int64
	Name            string
	Provider        string
	AccountName     string
	AccountNoMasked string
	Currency        string
	QrFileID        int64
	Scope           string
	EventID         *int64
	Active          bool
	CreatedBy       *int64
	CreatedAt       time.Time
}

type PaymentException struct {
	ID                   int64
	ExceptionNo          string
	Domain               string
	Type                 string
	RegOrderID           *int64
	MerchOrderID         *int64
	ReceiptID            int64
	AmountCents          int64
	Status               string
	Resolution           *string
	ResolutionNote       *string
	SettledRegRefundID   *int64
	SettledMerchRefundID *int64
	ResolvedBy           *int64
	ResolvedAt           *time.Time
	Note                 *string
	CreatedAt            time.Time
}

type PaymentProof struct {
	ID                  int64
	ProofNo             string
	RegOrderID          *int64
	MerchOrderID        *int64
	PaymentAccountID    int64
	FileID              int64
	SubmittedByUserID   *int64
	DeclaredAmountCents int64
	DeclaredCurrency    string
	BankTxnRef          string
	DeclaredPaidAt      *time.Time
	PayerName           *string
	PayerAccountMasked  *string
	Remark              *string
	IsLate              bool
	DupFileHit          bool
	Status              string
	ReviewedBy          *int64
	ReviewedAt          *time.Time
	RejectCode          *string
	RejectReason        *string
	CreatedAt           time.Time
}

type PaymentReceipt struct {
	ID               int64
	PaymentAccountID int64
	TxnRef           string
	AmountCents      int64
	Currency         string
	ReceivedAt       time.Time
	ProofID          *int64
	RegOrderID       *int64
	MerchOrderID     *int64
	MatchStatus      string
	RecordedByType   string
	RecordedBy       *int64
	CreatedAt        time.Time
}

type Photo struct {
	ID              int64
	BatchID         int64
	EventID         int64
	OriginalFileID  int64
	PreviewKey      *string
	ThumbKey        *string
	TakenAt         *time.Time
	Label           *string
	Status          string
	TakenDownReason *string
	TakenDownBy     *int64
	TakenDownAt     *time.Time
	CreatedAt       time.Time
}

type PhotoBatch struct {
	ID             int64
	EventID        int64
	Name           string
	PhotographerID int64
	PhotoCount     int32
	CreatedAt      time.Time
}

type PhotoBibTag struct {
	ID            int64
	PhotoID       int64
	EventID       int64
	BibNumber     int32
	TaggedBy      int64
	TaggedAt      time.Time
	Removed       bool
	RemovedBy     *int64
	RemovedAt     *time.Time
	RemovedReason *string
}

type PhotoRemovalRequest struct {
	ID         int64
	PhotoID    int64
	UserID     *int64
	Contact    string
	Reason     string
	Status     string
	ReviewedBy *int64
	ReviewedAt *time.Time
	ReviewNote *string
	CreatedAt  time.Time
}

type PhotoUserAction struct {
	ID        int64
	PhotoID   int64
	UserID    int64
	Action    string
	SponsorID *int64
	CreatedAt time.Time
}

type PriceRule struct {
	ID            int64
	EventID       int64
	Name          []byte
	Audience      string
	PriceCents    int64
	Currency      string
	Quota         *int32
	UsedCount     int32
	ReservedCount int32
	SaleStartsAt  *time.Time
	SaleEndsAt    *time.Time
	SortOrder     int16
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type RacePackConflict struct {
	ID             int64
	RegistrationID int64
	Status         string
	KeptScanLogID  *int64
	DecidedBy      *int64
	DecidedAt      *time.Time
	DecisionReason *string
	CreatedAt      time.Time
}

type RacePackFact struct {
	RegistrationID int64
	Picked         bool
	PickedAt       *time.Time
	PickedBy       *int64
	DeviceID       *string
	OfflineSynced  bool
	IDVerified     bool
	VerifiedAt     *time.Time
	VerifiedBy     *int64
	UpdatedAt      time.Time
}

type RacePackScanLog struct {
	ID             int64
	ClientEventID  pgtype.UUID
	RegistrationID int64
	EventID        int64
	Action         string
	Outcome        string
	Reason         *string
	StaffID        int64
	DeviceID       string
	Offline        bool
	OccurredAt     time.Time
	SyncedAt       time.Time
}

type Reconciliation struct {
	ID               int64
	PaymentAccountID int64
	BizDate          time.Time
	BankTotalCents   int64
	SystemTotalCents int64
	MatchedCount     int32
	Status           string
	ClosedBy         *int64
	ClosedAt         *time.Time
	CreatedAt        time.Time
}

type ReconciliationDiscrepancy struct {
	ID               int64
	ReconciliationID int64
	Type             string
	StatementLineID  *int64
	ReceiptID        *int64
	AmountCents      int64
	Status           string
	Resolution       *string
	EvidenceFileID   *int64
	ResolvedBy       *int64
	ResolvedAt       *time.Time
	Note             *string
}

type RefundCorrection struct {
	ID                   int64
	CorrectionNo         string
	OrderID              int64
	ParticipantID        int64
	SourceRefundID       int64
	Type                 string
	ShouldRefundCents    int64
	SettledCents         int64
	VarianceCents        *int64
	Status               string
	Resolution           *string
	SupplementalRefundID *int64
	RecoveredCents       *int64
	EvidenceFileID       *int64
	CreatedBy            int64
	ResolvedBy           *int64
	ResolvedAt           *time.Time
	CreatedAt            time.Time
}

type RegOrder struct {
	ID                     int64
	OrderNo                string
	EventID                int64
	BuyerUserID            *int64
	BuyerName              string
	BuyerPhoneE164         string
	BuyerEmail             *string
	Status                 string
	ReservationState       string
	ReservationReleaseKind *string
	ListAmountCents        int64
	DiscountCents          int64
	IdentOffsetCents       int16
	AmountCents            int64
	Currency               string
	CouponID               *int64
	PaymentAccountID       *int64
	DeadlineAt             *time.Time
	PaidAt                 *time.Time
	ExpiredAt              *time.Time
	CancelledAt            *time.Time
	CancelReason           *string
	Source                 string
	Archived               bool
	Version                int32
	CreatedAt              time.Time
	UpdatedAt              time.Time
}

type RegRefund struct {
	ID                 int64
	RefundNo           string
	OrderID            int64
	ParticipantID      *int64
	Kind               string
	RefundType         string
	SourceExceptionID  *int64
	SourceCorrectionID *int64
	RequestedCents     int64
	ApprovedCents      *int64
	SettledCents       *int64
	Currency           string
	Status             string
	Reason             string
	InitiatedByRole    string
	RequestedBy        int64
	ApprovedBy         *int64
	ApprovedAt         *time.Time
	SettledBy          *int64
	SettledAt          *time.Time
	PayoutMethod       *string
	PayeeAccountEnc    []byte
	PayoutTxnRef       *string
	PayoutProofFileID  *int64
	RejectedBy         *int64
	RejectedAt         *time.Time
	RejectReason       *string
	UserConfirmation   *string
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type Registration struct {
	ID                 int64
	RegNo              string
	OrderParticipantID int64
	EventID            int64
	CategoryID         int64
	Status             string
	CancelReason       *string
	TicketCode         string
	HolderID           pgtype.UUID
	UserID             *int64
	FullName           string
	Gender             string
	BirthDate          time.Time
	Nationality        string
	IDType             *string
	IDNoEnc            []byte
	IDNoHash           []byte
	PhoneE164          *string
	Email              *string
	EmergencyName      *string
	EmergencyPhone     *string
	TshirtSize         *string
	ConfirmedAt        *time.Time
	Version            int32
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type RegistrationChange struct {
	ID             int64
	RegistrationID int64
	ChangeType     string
	BeforeData     []byte
	AfterData      []byte
	FromHolderID   pgtype.UUID
	ToHolderID     pgtype.UUID
	Reason         *string
	ActorType      string
	ActorID        *int64
	CreatedAt      time.Time
}

type Result struct {
	ID             int64
	BatchID        int64
	EventID        int64
	CategoryID     int64
	BibNumber      int32
	RegistrationID *int64
	RunnerUserID   *int64
	NameSnapshot   string
	Gender         *string
	AgeGroup       *string
	Status         string
	GunTimeMs      *int32
	NetTimeMs      *int32
	StartTime      pgtype.Time
	OverallRank    *int32
	GenderRank     *int32
	AgeGroupRank   *int32
	Splits         []byte
	Note           *string
}

type ResultBatch struct {
	ID              int64
	EventID         int64
	CategoryID      int64
	Status          string
	ImportJobID     *int64
	SourceFileName  string
	RowCount        int32
	BadRowCount     int32
	BadRowsIgnored  bool
	CreatedBy       int64
	ValidatedBy     *int64
	ValidatedAt     *time.Time
	PublishedBy     *int64
	PublishedAt     *time.Time
	UnpublishedBy   *int64
	UnpublishedAt   *time.Time
	UnpublishReason *string
	CreatedAt       time.Time
}

type ResultClaimCase struct {
	ID             int64
	CaseNo         string
	ResultID       int64
	UserID         int64
	Evidence       string
	EvidenceFileID *int64
	Status         string
	ReceivedBy     int64
	DecidedBy      *int64
	DecidedAt      *time.Time
	DecisionNote   *string
	CreatedAt      time.Time
}

type RunnerProfile struct {
	ID             int64
	UserID         int64
	FullName       string
	Gender         string
	BirthDate      time.Time
	Nationality    string
	IDType         *string
	IDNoEnc        []byte
	IDNoHash       []byte
	PhoneE164      *string
	Email          *string
	EmergencyName  *string
	EmergencyPhone *string
	TshirtSize     *string
	IsSelf         bool
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Session struct {
	ID          int64
	SubjectType string
	SubjectID   int64
	TokenHash   []byte
	ExpiresAt   time.Time
	RevokedAt   *time.Time
	Ip          *netip.Addr
	UserAgent   *string
	CreatedAt   time.Time
}

type Sponsor struct {
	ID         int64
	Name       string
	LogoFileID *int64
	CreatedAt  time.Time
}

type Staff struct {
	ID            int64
	Username      string
	FullName      string
	Role          string
	PasswordHash  string
	TotpSecretEnc []byte
	Status        string
	LastLoginAt   *time.Time
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type StaffEventAssignment struct {
	ID         int64
	StaffID    int64
	EventID    int64
	ValidFrom  time.Time
	ValidUntil time.Time
	Enabled    bool
	CreatedBy  *int64
	CreatedAt  time.Time
}

type Story struct {
	ID           int64
	UserID       int64
	EventID      *int64
	ResultID     *int64
	Title        string
	Body         string
	Tags         []string
	CoverFileID  *int64
	LikeCount    int32
	CommentCount int32
	Status       string
	CreatedAt    time.Time
}

type StoryComment struct {
	ID        int64
	StoryID   int64
	UserID    int64
	Body      string
	Status    string
	CreatedAt time.Time
}

type StoryLike struct {
	StoryID   int64
	UserID    int64
	CreatedAt time.Time
}

type SupportRequest struct {
	ID            int64
	RequestNo     string
	Type          string
	UserID        *int64
	RegOrderID    *int64
	ParticipantID *int64
	MerchOrderID  *int64
	Reason        string
	Contact       string
	Status        string
	HandledBy     *int64
	HandledAt     *time.Time
	RegRefundID   *int64
	MerchRefundID *int64
	CreatedAt     time.Time
}

type SystemSetting struct {
	Key       string
	Value     []byte
	UpdatedBy *int64
	UpdatedAt time.Time
}

type User struct {
	ID               int64
	PhoneE164        *string
	Email            *string
	TelegramUserID   *int64
	TelegramUsername *string
	DisplayName      *string
	Locale           string
	Status           string
	LastLoginAt      *time.Time
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type WaitlistEntry struct {
	ID               int64
	EventID          int64
	CategoryID       int64
	UserID           *int64
	FullName         string
	PhoneE164        string
	Status           string
	PromotedSignupID *int64
	CreatedAt        time.Time
}
