// Package apigen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package apigen

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for Access.
const (
	AccessRead  Access = "read"
	AccessWrite Access = "write"
)

// Valid indicates whether the value is a known member of the Access enum.
func (e Access) Valid() bool {
	switch e {
	case AccessRead:
		return true
	case AccessWrite:
		return true
	default:
		return false
	}
}

// Defines values for AdminEventEventType.
const (
	AdminEventEventTypeFREEACTIVITY AdminEventEventType = "FREE_ACTIVITY"
	AdminEventEventTypeRACE         AdminEventEventType = "RACE"
)

// Valid indicates whether the value is a known member of the AdminEventEventType enum.
func (e AdminEventEventType) Valid() bool {
	switch e {
	case AdminEventEventTypeFREEACTIVITY:
		return true
	case AdminEventEventTypeRACE:
		return true
	default:
		return false
	}
}

// Defines values for AdminEventOrganizerType.
const (
	AdminEventOrganizerTypeOFFICIAL AdminEventOrganizerType = "OFFICIAL"
	AdminEventOrganizerTypePARTNER  AdminEventOrganizerType = "PARTNER"
)

// Valid indicates whether the value is a known member of the AdminEventOrganizerType enum.
func (e AdminEventOrganizerType) Valid() bool {
	switch e {
	case AdminEventOrganizerTypeOFFICIAL:
		return true
	case AdminEventOrganizerTypePARTNER:
		return true
	default:
		return false
	}
}

// Defines values for AdminEventStatus.
const (
	AdminEventStatusDRAFT     AdminEventStatus = "DRAFT"
	AdminEventStatusPUBLISHED AdminEventStatus = "PUBLISHED"
)

// Valid indicates whether the value is a known member of the AdminEventStatus enum.
func (e AdminEventStatus) Valid() bool {
	switch e {
	case AdminEventStatusDRAFT:
		return true
	case AdminEventStatusPUBLISHED:
		return true
	default:
		return false
	}
}

// Defines values for CreateEventRequestEventType.
const (
	CreateEventRequestEventTypeFREEACTIVITY CreateEventRequestEventType = "FREE_ACTIVITY"
	CreateEventRequestEventTypeRACE         CreateEventRequestEventType = "RACE"
)

// Valid indicates whether the value is a known member of the CreateEventRequestEventType enum.
func (e CreateEventRequestEventType) Valid() bool {
	switch e {
	case CreateEventRequestEventTypeFREEACTIVITY:
		return true
	case CreateEventRequestEventTypeRACE:
		return true
	default:
		return false
	}
}

// Defines values for CreateEventRequestOrganizerType.
const (
	CreateEventRequestOrganizerTypeOFFICIAL CreateEventRequestOrganizerType = "OFFICIAL"
	CreateEventRequestOrganizerTypePARTNER  CreateEventRequestOrganizerType = "PARTNER"
)

// Valid indicates whether the value is a known member of the CreateEventRequestOrganizerType enum.
func (e CreateEventRequestOrganizerType) Valid() bool {
	switch e {
	case CreateEventRequestOrganizerTypeOFFICIAL:
		return true
	case CreateEventRequestOrganizerTypePARTNER:
		return true
	default:
		return false
	}
}

// Defines values for PriceAudience.
const (
	PriceAudienceALL   PriceAudience = "ALL"
	PriceAudienceLOCAL PriceAudience = "LOCAL"
)

// Valid indicates whether the value is a known member of the PriceAudience enum.
func (e PriceAudience) Valid() bool {
	switch e {
	case PriceAudienceALL:
		return true
	case PriceAudienceLOCAL:
		return true
	default:
		return false
	}
}

// Defines values for Role.
const (
	RoleADMIN          Role = "ADMIN"
	RoleFINANCE        Role = "FINANCE"
	RoleOPS            Role = "OPS"
	RolePHOTOGRAPHER   Role = "PHOTOGRAPHER"
	RoleRACESTAFF      Role = "RACE_STAFF"
	RoleRACESUPERVISOR Role = "RACE_SUPERVISOR"
	RoleSUPPORT        Role = "SUPPORT"
)

// Valid indicates whether the value is a known member of the Role enum.
func (e Role) Valid() bool {
	switch e {
	case RoleADMIN:
		return true
	case RoleFINANCE:
		return true
	case RoleOPS:
		return true
	case RolePHOTOGRAPHER:
		return true
	case RoleRACESTAFF:
		return true
	case RoleRACESUPERVISOR:
		return true
	case RoleSUPPORT:
		return true
	default:
		return false
	}
}

// Access defines model for Access.
type Access string

// AdminCategory defines model for AdminCategory.
type AdminCategory struct {
	Capacity  int32         `json:"capacity"`
	Code      string        `json:"code"`
	CutoffAt  *time.Time    `json:"cutoffAt"`
	DistanceM int32         `json:"distanceM"`
	Id        int64         `json:"id"`
	Name      LocalizedText `json:"name"`
	StartAt   *time.Time    `json:"startAt"`
}

// AdminEvent defines model for AdminEvent.
type AdminEvent struct {
	Categories           []AdminCategory         `json:"categories"`
	City                 string                  `json:"city"`
	EventType            AdminEventEventType     `json:"eventType"`
	Id                   int64                   `json:"id"`
	Name                 LocalizedText           `json:"name"`
	OrganizerType        AdminEventOrganizerType `json:"organizerType"`
	PublicVisible        bool                    `json:"publicVisible"`
	PublishedAt          *time.Time              `json:"publishedAt"`
	RaceDate             openapi_types.Date      `json:"raceDate"`
	RegistrationClosesAt *time.Time              `json:"registrationClosesAt"`
	RegistrationOpen     bool                    `json:"registrationOpen"`
	RegistrationOpensAt  *time.Time              `json:"registrationOpensAt"`
	Slug                 string                  `json:"slug"`
	Status               AdminEventStatus        `json:"status"`
	Timezone             string                  `json:"timezone"`
}

// AdminEventEventType defines model for AdminEvent.EventType.
type AdminEventEventType string

// AdminEventOrganizerType defines model for AdminEvent.OrganizerType.
type AdminEventOrganizerType string

// AdminEventStatus defines model for AdminEvent.Status.
type AdminEventStatus string

// AdminEventList defines model for AdminEventList.
type AdminEventList struct {
	Items []AdminEvent `json:"items"`
}

// CreateCategoryRequest defines model for CreateCategoryRequest.
type CreateCategoryRequest struct {
	Capacity  int32         `json:"capacity"`
	Code      string        `json:"code"`
	CutoffAt  *time.Time    `json:"cutoffAt,omitempty"`
	DistanceM int32         `json:"distanceM"`
	Name      LocalizedText `json:"name"`
	StartAt   *time.Time    `json:"startAt,omitempty"`
}

// CreateEventRequest defines model for CreateEventRequest.
type CreateEventRequest struct {
	Categories    []CreateCategoryRequest         `json:"categories"`
	City          string                          `json:"city"`
	EventType     CreateEventRequestEventType     `json:"eventType"`
	Name          LocalizedText                   `json:"name"`
	OrganizerType CreateEventRequestOrganizerType `json:"organizerType"`
	RaceDate      openapi_types.Date              `json:"raceDate"`
	Slug          string                          `json:"slug"`
}

// CreateEventRequestEventType defines model for CreateEventRequest.EventType.
type CreateEventRequestEventType string

// CreateEventRequestOrganizerType defines model for CreateEventRequest.OrganizerType.
type CreateEventRequestOrganizerType string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error struct {
		Code    string             `json:"code"`
		Fields  *map[string]string `json:"fields,omitempty"`
		Message string             `json:"message"`
	} `json:"error"`
}

// Health defines model for Health.
type Health struct {
	Status string `json:"status"`
}

// LocalizedText defines model for LocalizedText.
type LocalizedText struct {
	En *string `json:"en,omitempty"`
	Km *string `json:"km,omitempty"`
	Zh *string `json:"zh,omitempty"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// Me defines model for Me.
type Me struct {
	Permissions map[string]Access `json:"permissions"`
	Staff       Staff             `json:"staff"`
}

// PriceAudience defines model for PriceAudience.
type PriceAudience string

// PriceRule defines model for PriceRule.
type PriceRule struct {
	Audience      PriceAudience `json:"audience"`
	CategoryIds   []int64       `json:"categoryIds"`
	Currency      string        `json:"currency"`
	EventId       int64         `json:"eventId"`
	Id            int64         `json:"id"`
	Name          LocalizedText `json:"name"`
	PriceCents    int64         `json:"priceCents"`
	Quota         *int32        `json:"quota"`
	ReservedCount int32         `json:"reservedCount"`
	SaleEndsAt    *time.Time    `json:"saleEndsAt"`
	SaleStartsAt  *time.Time    `json:"saleStartsAt"`
	SortOrder     int32         `json:"sortOrder"`
	UsedCount     int32         `json:"usedCount"`
}

// PriceRuleInput defines model for PriceRuleInput.
type PriceRuleInput struct {
	Audience     PriceAudience `json:"audience"`
	CategoryIds  []int64       `json:"categoryIds"`
	Name         LocalizedText `json:"name"`
	PriceCents   int64         `json:"priceCents"`
	Quota        *int32        `json:"quota,omitempty"`
	SaleEndsAt   *time.Time    `json:"saleEndsAt,omitempty"`
	SaleStartsAt *time.Time    `json:"saleStartsAt,omitempty"`
	SortOrder    *int32        `json:"sortOrder,omitempty"`
}

// PriceRuleList defines model for PriceRuleList.
type PriceRuleList struct {
	Items []PriceRule `json:"items"`
}

// PublicCategory defines model for PublicCategory.
type PublicCategory struct {
	Capacity  int32     `json:"capacity"`
	Code      string    `json:"code"`
	CutoffAt  time.Time `json:"cutoffAt"`
	DistanceM int32     `json:"distanceM"`
	Name      string    `json:"name"`
	StartAt   time.Time `json:"startAt"`
}

// PublicEvent defines model for PublicEvent.
type PublicEvent struct {
	Categories []PublicCategory   `json:"categories"`
	City       string             `json:"city"`
	Name       string             `json:"name"`
	RaceDate   openapi_types.Date `json:"raceDate"`
	Slug       string             `json:"slug"`
}

// PublicEventList defines model for PublicEventList.
type PublicEventList struct {
	Items []PublicEvent `json:"items"`
}

// Role defines model for Role.
type Role string

// Staff defines model for Staff.
type Staff struct {
	FullName string `json:"fullName"`
	Id       int64  `json:"id"`
	Role     Role   `json:"role"`
	Username string `json:"username"`
}

// UpdateEventRegistrationRequest defines model for UpdateEventRegistrationRequest.
type UpdateEventRegistrationRequest struct {
	ClosesAt *time.Time `json:"closesAt,omitempty"`
	Open     bool       `json:"open"`
	OpensAt  *time.Time `json:"opensAt,omitempty"`
}

// AdminLoginJSONRequestBody defines body for AdminLogin for application/json ContentType.
type AdminLoginJSONRequestBody = LoginRequest

// AdminCreateEventJSONRequestBody defines body for AdminCreateEvent for application/json ContentType.
type AdminCreateEventJSONRequestBody = CreateEventRequest

// AdminCreatePriceRuleJSONRequestBody defines body for AdminCreatePriceRule for application/json ContentType.
type AdminCreatePriceRuleJSONRequestBody = PriceRuleInput

// AdminUpdateEventRegistrationJSONRequestBody defines body for AdminUpdateEventRegistration for application/json ContentType.
type AdminUpdateEventRegistrationJSONRequestBody = UpdateEventRegistrationRequest

// AdminUpdatePriceRuleJSONRequestBody defines body for AdminUpdatePriceRule for application/json ContentType.
type AdminUpdatePriceRuleJSONRequestBody = PriceRuleInput

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// AdminLogin 员工登录
	// (POST /admin/auth/login)
	AdminLogin(c *gin.Context)
	// AdminLogout 退出登录
	// (POST /admin/auth/logout)
	AdminLogout(c *gin.Context)
	// AdminListEvents 后台赛事列表（名称返回三语）
	// (GET /admin/events)
	AdminListEvents(c *gin.Context)
	// AdminCreateEvent 新建草稿赛事及组别
	// (POST /admin/events)
	AdminCreateEvent(c *gin.Context)
	// AdminGetEvent 后台赛事详情（任意状态，含报名设置与组别）
	// (GET /admin/events/{id})
	AdminGetEvent(c *gin.Context, id int64)
	// AdminListPriceRules 赛事的价格档列表（含关联组别与计数）
	// (GET /admin/events/{id}/price-rules)
	AdminListPriceRules(c *gin.Context, id int64)
	// AdminCreatePriceRule 新建价格档
	// (POST /admin/events/{id}/price-rules)
	AdminCreatePriceRule(c *gin.Context, id int64)
	// AdminPublishEvent 发布赛事（发布前校验）
	// (POST /admin/events/{id}/publish)
	AdminPublishEvent(c *gin.Context, id int64)
	// AdminUpdateEventRegistration 修改报名开关与报名时间（开放前校验发布状态、价格档与收款账户）
	// (PATCH /admin/events/{id}/registration)
	AdminUpdateEventRegistration(c *gin.Context, id int64)
	// AdminGetMe 当前员工与权限
	// (GET /admin/me)
	AdminGetMe(c *gin.Context)
	// AdminUpdatePriceRule 修改价格档（已有占用时不可改价格、人群、关联组别）
	// (PUT /admin/price-rules/{id})
	AdminUpdatePriceRule(c *gin.Context, id int64)
	// ListPublicEvents 已发布且公开展示的赛事列表，文案按请求语言返回
	// (GET /events)
	ListPublicEvents(c *gin.Context)
	// GetPublicEvent 赛事详情（含组别）
	// (GET /events/{slug})
	GetPublicEvent(c *gin.Context, slug string)
	// GetHealthz 进程存活检查
	// (GET /healthz)
	GetHealthz(c *gin.Context)
	// GetReadyz 数据库连通检查
	// (GET /readyz)
	GetReadyz(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// AdminLogin operation middleware
func (siw *ServerInterfaceWrapper) AdminLogin(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AdminLogin(c)
}

// AdminLogout operation middleware
func (siw *ServerInterfaceWrapper) AdminLogout(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AdminLogout(c)
}

// AdminListEvents operation middleware
func (siw *ServerInterfaceWrapper) AdminListEvents(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AdminListEvents(c)
}

// AdminCreateEvent operation middleware
func (siw *ServerInterfaceWrapper) AdminCreateEvent(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AdminCreateEvent(c)
}

// AdminGetEvent operation middleware
func (siw *ServerInterfaceWrapper) AdminGetEvent(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AdminGetEvent(c, id)
}

// AdminListPriceRules operation middleware
func (siw *ServerInterfaceWrapper) AdminListPriceRules(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AdminListPriceRules(c, id)
}

// AdminCreatePriceRule operation middleware
func (siw *ServerInterfaceWrapper) AdminCreatePriceRule(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AdminCreatePriceRule(c, id)
}

// AdminPublishEvent operation middleware
func (siw *ServerInterfaceWrapper) AdminPublishEvent(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AdminPublishEvent(c, id)
}

// AdminUpdateEventRegistration operation middleware
func (siw *ServerInterfaceWrapper) AdminUpdateEventRegistration(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AdminUpdateEventRegistration(c, id)
}

// AdminGetMe operation middleware
func (siw *ServerInterfaceWrapper) AdminGetMe(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AdminGetMe(c)
}

// AdminUpdatePriceRule operation middleware
func (siw *ServerInterfaceWrapper) AdminUpdatePriceRule(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AdminUpdatePriceRule(c, id)
}

// ListPublicEvents operation middleware
func (siw *ServerInterfaceWrapper) ListPublicEvents(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListPublicEvents(c)
}

// GetPublicEvent operation middleware
func (siw *ServerInterfaceWrapper) GetPublicEvent(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "slug" -------------
	var slug string

	err = runtime.BindStyledParameterWithOptions("simple", "slug", c.Param("slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter slug: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetPublicEvent(c, slug)
}

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetHealthz(c)
}

// GetReadyz operation middleware
func (siw *ServerInterfaceWrapper) GetReadyz(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetReadyz(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/healthz", wrapper.GetHealthz)
	router.GET(options.BaseURL+"/readyz", wrapper.GetReadyz)
	router.POST(options.BaseURL+"/admin/auth/login", wrapper.AdminLogin)
	router.POST(options.BaseURL+"/admin/auth/logout", wrapper.AdminLogout)
	router.GET(options.BaseURL+"/admin/me", wrapper.AdminGetMe)
	router.GET(options.BaseURL+"/events", wrapper.ListPublicEvents)
	router.GET(options.BaseURL+"/events/:slug", wrapper.GetPublicEvent)
	router.GET(options.BaseURL+"/admin/events", wrapper.AdminListEvents)
	router.POST(options.BaseURL+"/admin/events", wrapper.AdminCreateEvent)
	router.GET(options.BaseURL+"/admin/events/:id", wrapper.AdminGetEvent)
	router.PATCH(options.BaseURL+"/admin/events/:id/registration", wrapper.AdminUpdateEventRegistration)
	router.POST(options.BaseURL+"/admin/events/:id/publish", wrapper.AdminPublishEvent)
	router.GET(options.BaseURL+"/admin/events/:id/price-rules", wrapper.AdminListPriceRules)
	router.POST(options.BaseURL+"/admin/events/:id/price-rules", wrapper.AdminCreatePriceRule)
	router.PUT(options.BaseURL+"/admin/price-rules/:id", wrapper.AdminUpdatePriceRule)
}

type AdminLoginRequestObject struct {
	Body *AdminLoginJSONRequestBody
}

type AdminLoginResponseObject interface {
	VisitAdminLoginResponse(w http.ResponseWriter) error
}

type AdminLogin200JSONResponse Me

func (response AdminLogin200JSONResponse) VisitAdminLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type AdminLogindefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response AdminLogindefaultJSONResponse) VisitAdminLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type AdminLogoutRequestObject struct {
}

type AdminLogoutResponseObject interface {
	VisitAdminLogoutResponse(w http.ResponseWriter) error
}

type AdminLogout204Response struct {
}

func (response AdminLogout204Response) VisitAdminLogoutResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type AdminLogoutdefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response AdminLogoutdefaultJSONResponse) VisitAdminLogoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type AdminListEventsRequestObject struct {
}

type AdminListEventsResponseObject interface {
	VisitAdminListEventsResponse(w http.ResponseWriter) error
}

type AdminListEvents200JSONResponse AdminEventList

func (response AdminListEvents200JSONResponse) VisitAdminListEventsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type AdminListEventsdefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response AdminListEventsdefaultJSONResponse) VisitAdminListEventsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type AdminCreateEventRequestObject struct {
	Body *AdminCreateEventJSONRequestBody
}

type AdminCreateEventResponseObject interface {
	VisitAdminCreateEventResponse(w http.ResponseWriter) error
}

type AdminCreateEvent201JSONResponse AdminEvent

func (response AdminCreateEvent201JSONResponse) VisitAdminCreateEventResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type AdminCreateEventdefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response AdminCreateEventdefaultJSONResponse) VisitAdminCreateEventResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type AdminGetEventRequestObject struct {
	Id int64 `json:"id"`
}

type AdminGetEventResponseObject interface {
	VisitAdminGetEventResponse(w http.ResponseWriter) error
}

type AdminGetEvent200JSONResponse AdminEvent

func (response AdminGetEvent200JSONResponse) VisitAdminGetEventResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type AdminGetEventdefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response AdminGetEventdefaultJSONResponse) VisitAdminGetEventResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type AdminListPriceRulesRequestObject struct {
	Id int64 `json:"id"`
}

type AdminListPriceRulesResponseObject interface {
	VisitAdminListPriceRulesResponse(w http.ResponseWriter) error
}

type AdminListPriceRules200JSONResponse PriceRuleList

func (response AdminListPriceRules200JSONResponse) VisitAdminListPriceRulesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type AdminListPriceRulesdefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response AdminListPriceRulesdefaultJSONResponse) VisitAdminListPriceRulesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type AdminCreatePriceRuleRequestObject struct {
	Id   int64 `json:"id"`
	Body *AdminCreatePriceRuleJSONRequestBody
}

type AdminCreatePriceRuleResponseObject interface {
	VisitAdminCreatePriceRuleResponse(w http.ResponseWriter) error
}

type AdminCreatePriceRule201JSONResponse PriceRule

func (response AdminCreatePriceRule201JSONResponse) VisitAdminCreatePriceRuleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type AdminCreatePriceRuledefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response AdminCreatePriceRuledefaultJSONResponse) VisitAdminCreatePriceRuleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type AdminPublishEventRequestObject struct {
	Id int64 `json:"id"`
}

type AdminPublishEventResponseObject interface {
	VisitAdminPublishEventResponse(w http.ResponseWriter) error
}

type AdminPublishEvent200JSONResponse AdminEvent

func (response AdminPublishEvent200JSONResponse) VisitAdminPublishEventResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type AdminPublishEventdefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response AdminPublishEventdefaultJSONResponse) VisitAdminPublishEventResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type AdminUpdateEventRegistrationRequestObject struct {
	Id   int64 `json:"id"`
	Body *AdminUpdateEventRegistrationJSONRequestBody
}

type AdminUpdateEventRegistrationResponseObject interface {
	VisitAdminUpdateEventRegistrationResponse(w http.ResponseWriter) error
}

type AdminUpdateEventRegistration200JSONResponse AdminEvent

func (response AdminUpdateEventRegistration200JSONResponse) VisitAdminUpdateEventRegistrationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type AdminUpdateEventRegistrationdefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response AdminUpdateEventRegistrationdefaultJSONResponse) VisitAdminUpdateEventRegistrationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type AdminGetMeRequestObject struct {
}

type AdminGetMeResponseObject interface {
	VisitAdminGetMeResponse(w http.ResponseWriter) error
}

type AdminGetMe200JSONResponse Me

func (response AdminGetMe200JSONResponse) VisitAdminGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type AdminGetMedefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response AdminGetMedefaultJSONResponse) VisitAdminGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type AdminUpdatePriceRuleRequestObject struct {
	Id   int64 `json:"id"`
	Body *AdminUpdatePriceRuleJSONRequestBody
}

type AdminUpdatePriceRuleResponseObject interface {
	VisitAdminUpdatePriceRuleResponse(w http.ResponseWriter) error
}

type AdminUpdatePriceRule200JSONResponse PriceRule

func (response AdminUpdatePriceRule200JSONResponse) VisitAdminUpdatePriceRuleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type AdminUpdatePriceRuledefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response AdminUpdatePriceRuledefaultJSONResponse) VisitAdminUpdatePriceRuleResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ListPublicEventsRequestObject struct {
}

type ListPublicEventsResponseObject interface {
	VisitListPublicEventsResponse(w http.ResponseWriter) error
}

type ListPublicEvents200JSONResponse PublicEventList

func (response ListPublicEvents200JSONResponse) VisitListPublicEventsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListPublicEventsdefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response ListPublicEventsdefaultJSONResponse) VisitListPublicEventsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetPublicEventRequestObject struct {
	Slug string `json:"slug"`
}

type GetPublicEventResponseObject interface {
	VisitGetPublicEventResponse(w http.ResponseWriter) error
}

type GetPublicEvent200JSONResponse PublicEvent

func (response GetPublicEvent200JSONResponse) VisitGetPublicEventResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetPublicEventdefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response GetPublicEventdefaultJSONResponse) VisitGetPublicEventResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthzRequestObject struct {
}

type GetHealthzResponseObject interface {
	VisitGetHealthzResponse(w http.ResponseWriter) error
}

type GetHealthz200JSONResponse Health

func (response GetHealthz200JSONResponse) VisitGetHealthzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthzdefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response GetHealthzdefaultJSONResponse) VisitGetHealthzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetReadyzRequestObject struct {
}

type GetReadyzResponseObject interface {
	VisitGetReadyzResponse(w http.ResponseWriter) error
}

type GetReadyz200JSONResponse Health

func (response GetReadyz200JSONResponse) VisitGetReadyzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetReadyz503JSONResponse Health

func (response GetReadyz503JSONResponse) VisitGetReadyzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type GetReadyzdefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response GetReadyzdefaultJSONResponse) VisitGetReadyzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// AdminLogin 员工登录
	// (POST /admin/auth/login)
	AdminLogin(ctx context.Context, request AdminLoginRequestObject) (AdminLoginResponseObject, error)
	// AdminLogout 退出登录
	// (POST /admin/auth/logout)
	AdminLogout(ctx context.Context, request AdminLogoutRequestObject) (AdminLogoutResponseObject, error)
	// AdminListEvents 后台赛事列表（名称返回三语）
	// (GET /admin/events)
	AdminListEvents(ctx context.Context, request AdminListEventsRequestObject) (AdminListEventsResponseObject, error)
	// AdminCreateEvent 新建草稿赛事及组别
	// (POST /admin/events)
	AdminCreateEvent(ctx context.Context, request AdminCreateEventRequestObject) (AdminCreateEventResponseObject, error)
	// AdminGetEvent 后台赛事详情（任意状态，含报名设置与组别）
	// (GET /admin/events/{id})
	AdminGetEvent(ctx context.Context, request AdminGetEventRequestObject) (AdminGetEventResponseObject, error)
	// AdminListPriceRules 赛事的价格档列表（含关联组别与计数）
	// (GET /admin/events/{id}/price-rules)
	AdminListPriceRules(ctx context.Context, request AdminListPriceRulesRequestObject) (AdminListPriceRulesResponseObject, error)
	// AdminCreatePriceRule 新建价格档
	// (POST /admin/events/{id}/price-rules)
	AdminCreatePriceRule(ctx context.Context, request AdminCreatePriceRuleRequestObject) (AdminCreatePriceRuleResponseObject, error)
	// AdminPublishEvent 发布赛事（发布前校验）
	// (POST /admin/events/{id}/publish)
	AdminPublishEvent(ctx context.Context, request AdminPublishEventRequestObject) (AdminPublishEventResponseObject, error)
	// AdminUpdateEventRegistration 修改报名开关与报名时间（开放前校验发布状态、价格档与收款账户）
	// (PATCH /admin/events/{id}/registration)
	AdminUpdateEventRegistration(ctx context.Context, request AdminUpdateEventRegistrationRequestObject) (AdminUpdateEventRegistrationResponseObject, error)
	// AdminGetMe 当前员工与权限
	// (GET /admin/me)
	AdminGetMe(ctx context.Context, request AdminGetMeRequestObject) (AdminGetMeResponseObject, error)
	// AdminUpdatePriceRule 修改价格档（已有占用时不可改价格、人群、关联组别）
	// (PUT /admin/price-rules/{id})
	AdminUpdatePriceRule(ctx context.Context, request AdminUpdatePriceRuleRequestObject) (AdminUpdatePriceRuleResponseObject, error)
	// ListPublicEvents 已发布且公开展示的赛事列表，文案按请求语言返回
	// (GET /events)
	ListPublicEvents(ctx context.Context, request ListPublicEventsRequestObject) (ListPublicEventsResponseObject, error)
	// GetPublicEvent 赛事详情（含组别）
	// (GET /events/{slug})
	GetPublicEvent(ctx context.Context, request GetPublicEventRequestObject) (GetPublicEventResponseObject, error)
	// GetHealthz 进程存活检查
	// (GET /healthz)
	GetHealthz(ctx context.Context, request GetHealthzRequestObject) (GetHealthzResponseObject, error)
	// GetReadyz 数据库连通检查
	// (GET /readyz)
	GetReadyz(ctx context.Context, request GetReadyzRequestObject) (GetReadyzResponseObject, error)
}

type StrictHandlerFunc func(ctx *gin.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictGinServerOptions struct {
	// RequestErrorHandlerFunc is called when a request cannot be parsed or
	// decoded. It is invoked for JSON bind failures, form parse/bind errors,
	// multipart reader errors, media type parse errors, missing multipart
	// boundaries, and request body read errors. The default returns 400.
	RequestErrorHandlerFunc func(ctx *gin.Context, err error)
	// HandlerErrorFunc is called when the application handler (or any
	// middleware wrapping it) returns a non-nil error. The default returns 500.
	HandlerErrorFunc func(ctx *gin.Context, err error)
	// ResponseErrorHandlerFunc is called when the response object fails to
	// serialize (Visit*Response returns an error) or when the handler returns
	// an unexpected response type. The default returns 500.
	ResponseErrorHandlerFunc func(ctx *gin.Context, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictGinServerOptions{
		RequestErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		},
		HandlerErrorFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
		ResponseErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictGinServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		}
	}
	if options.HandlerErrorFunc == nil {
		options.HandlerErrorFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictGinServerOptions
}

// AdminLogin operation middleware
func (sh *strictHandler) AdminLogin(ctx *gin.Context) {
	var request AdminLoginRequestObject

	var body AdminLoginJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.AdminLogin(ctx, request.(AdminLoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AdminLogin")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(AdminLoginResponseObject); ok {
		if err := validResponse.VisitAdminLoginResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AdminLogout operation middleware
func (sh *strictHandler) AdminLogout(ctx *gin.Context) {
	var request AdminLogoutRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.AdminLogout(ctx, request.(AdminLogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AdminLogout")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(AdminLogoutResponseObject); ok {
		if err := validResponse.VisitAdminLogoutResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AdminListEvents operation middleware
func (sh *strictHandler) AdminListEvents(ctx *gin.Context) {
	var request AdminListEventsRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.AdminListEvents(ctx, request.(AdminListEventsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AdminListEvents")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(AdminListEventsResponseObject); ok {
		if err := validResponse.VisitAdminListEventsResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AdminCreateEvent operation middleware
func (sh *strictHandler) AdminCreateEvent(ctx *gin.Context) {
	var request AdminCreateEventRequestObject

	var body AdminCreateEventJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.AdminCreateEvent(ctx, request.(AdminCreateEventRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AdminCreateEvent")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(AdminCreateEventResponseObject); ok {
		if err := validResponse.VisitAdminCreateEventResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AdminGetEvent operation middleware
func (sh *strictHandler) AdminGetEvent(ctx *gin.Context, id int64) {
	var request AdminGetEventRequestObject

	request.Id = id

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.AdminGetEvent(ctx, request.(AdminGetEventRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AdminGetEvent")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(AdminGetEventResponseObject); ok {
		if err := validResponse.VisitAdminGetEventResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AdminListPriceRules operation middleware
func (sh *strictHandler) AdminListPriceRules(ctx *gin.Context, id int64) {
	var request AdminListPriceRulesRequestObject

	request.Id = id

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.AdminListPriceRules(ctx, request.(AdminListPriceRulesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AdminListPriceRules")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(AdminListPriceRulesResponseObject); ok {
		if err := validResponse.VisitAdminListPriceRulesResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AdminCreatePriceRule operation middleware
func (sh *strictHandler) AdminCreatePriceRule(ctx *gin.Context, id int64) {
	var request AdminCreatePriceRuleRequestObject

	request.Id = id

	var body AdminCreatePriceRuleJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.AdminCreatePriceRule(ctx, request.(AdminCreatePriceRuleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AdminCreatePriceRule")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(AdminCreatePriceRuleResponseObject); ok {
		if err := validResponse.VisitAdminCreatePriceRuleResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AdminPublishEvent operation middleware
func (sh *strictHandler) AdminPublishEvent(ctx *gin.Context, id int64) {
	var request AdminPublishEventRequestObject

	request.Id = id

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.AdminPublishEvent(ctx, request.(AdminPublishEventRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AdminPublishEvent")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(AdminPublishEventResponseObject); ok {
		if err := validResponse.VisitAdminPublishEventResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AdminUpdateEventRegistration operation middleware
func (sh *strictHandler) AdminUpdateEventRegistration(ctx *gin.Context, id int64) {
	var request AdminUpdateEventRegistrationRequestObject

	request.Id = id

	var body AdminUpdateEventRegistrationJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.AdminUpdateEventRegistration(ctx, request.(AdminUpdateEventRegistrationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AdminUpdateEventRegistration")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(AdminUpdateEventRegistrationResponseObject); ok {
		if err := validResponse.VisitAdminUpdateEventRegistrationResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AdminGetMe operation middleware
func (sh *strictHandler) AdminGetMe(ctx *gin.Context) {
	var request AdminGetMeRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.AdminGetMe(ctx, request.(AdminGetMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AdminGetMe")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(AdminGetMeResponseObject); ok {
		if err := validResponse.VisitAdminGetMeResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AdminUpdatePriceRule operation middleware
func (sh *strictHandler) AdminUpdatePriceRule(ctx *gin.Context, id int64) {
	var request AdminUpdatePriceRuleRequestObject

	request.Id = id

	var body AdminUpdatePriceRuleJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.AdminUpdatePriceRule(ctx, request.(AdminUpdatePriceRuleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AdminUpdatePriceRule")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(AdminUpdatePriceRuleResponseObject); ok {
		if err := validResponse.VisitAdminUpdatePriceRuleResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListPublicEvents operation middleware
func (sh *strictHandler) ListPublicEvents(ctx *gin.Context) {
	var request ListPublicEventsRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListPublicEvents(ctx, request.(ListPublicEventsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListPublicEvents")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(ListPublicEventsResponseObject); ok {
		if err := validResponse.VisitListPublicEventsResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetPublicEvent operation middleware
func (sh *strictHandler) GetPublicEvent(ctx *gin.Context, slug string) {
	var request GetPublicEventRequestObject

	request.Slug = slug

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetPublicEvent(ctx, request.(GetPublicEventRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPublicEvent")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetPublicEventResponseObject); ok {
		if err := validResponse.VisitGetPublicEventResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealthz operation middleware
func (sh *strictHandler) GetHealthz(ctx *gin.Context) {
	var request GetHealthzRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealthz(ctx, request.(GetHealthzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealthz")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetHealthzResponseObject); ok {
		if err := validResponse.VisitGetHealthzResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetReadyz operation middleware
func (sh *strictHandler) GetReadyz(ctx *gin.Context) {
	var request GetReadyzRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetReadyz(ctx, request.(GetReadyzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetReadyz")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetReadyzResponseObject); ok {
		if err := validResponse.VisitGetReadyzResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}
