// Code generated by permgen from openapi/openapi.yaml. DO NOT EDIT.

package apigen

// AuthKind 表示一个接口需要的鉴权方式。
type AuthKind string

const (
	AuthNone       AuthKind = "none"
	AuthSession    AuthKind = "session"
	AuthPermission AuthKind = "permission"
	AuthApp        AuthKind = "app"
)

// OperationAuth 是单个接口的鉴权规则。
type OperationAuth struct {
	Kind       AuthKind
	Permission string
	Access     string
}

// OperationAuths 的键是 strict 中间件收到的 operationID（首字母大写的 operationId）。
var OperationAuths = map[string]OperationAuth{
	"AdminCreateCoupon":            {Kind: AuthPermission, Permission: "coupon_manage", Access: "write"},
	"AdminCreateEvent":             {Kind: AuthPermission, Permission: "event_config", Access: "write"},
	"AdminCreatePaymentAccount":    {Kind: AuthPermission, Permission: "payment_account_manage", Access: "write"},
	"AdminCreatePriceRule":         {Kind: AuthPermission, Permission: "price_config", Access: "write"},
	"AdminGetEvent":                {Kind: AuthPermission, Permission: "event_config", Access: "read"},
	"AdminGetMe":                   {Kind: AuthSession},
	"AdminListCoupons":             {Kind: AuthPermission, Permission: "coupon_manage", Access: "read"},
	"AdminListEvents":              {Kind: AuthPermission, Permission: "event_config", Access: "read"},
	"AdminListPaymentAccounts":     {Kind: AuthPermission, Permission: "payment_account_manage", Access: "read"},
	"AdminListPriceRules":          {Kind: AuthPermission, Permission: "price_config", Access: "read"},
	"AdminLogin":                   {Kind: AuthNone},
	"AdminLogout":                  {Kind: AuthSession},
	"AdminPublishEvent":            {Kind: AuthPermission, Permission: "event_publish", Access: "write"},
	"AdminUpdateCoupon":            {Kind: AuthPermission, Permission: "coupon_manage", Access: "write"},
	"AdminUpdateEventRegistration": {Kind: AuthPermission, Permission: "event_config", Access: "write"},
	"AdminUpdatePaymentAccount":    {Kind: AuthPermission, Permission: "payment_account_manage", Access: "write"},
	"AdminUpdatePriceRule":         {Kind: AuthPermission, Permission: "price_config", Access: "write"},
	"AppCreateOrder":               {Kind: AuthApp},
	"AppCreateProfile":             {Kind: AuthApp},
	"AppDeleteProfile":             {Kind: AuthApp},
	"AppGetConsent":                {Kind: AuthApp},
	"AppGetMe":                     {Kind: AuthApp},
	"AppListProfiles":              {Kind: AuthApp},
	"AppLoginTelegram":             {Kind: AuthNone},
	"AppLogout":                    {Kind: AuthApp},
	"AppQuote":                     {Kind: AuthApp},
	"AppUpdateProfile":             {Kind: AuthApp},
	"GetHealthz":                   {Kind: AuthNone},
	"GetPublicEvent":               {Kind: AuthNone},
	"GetPublicFile":                {Kind: AuthNone},
	"GetReadyz":                    {Kind: AuthNone},
	"ListPublicEvents":             {Kind: AuthNone},
}
