// Code generated by permgen from openapi/openapi.yaml. DO NOT EDIT.

package apigen

// AuthKind 表示一个接口需要的鉴权方式。
type AuthKind string

const (
	AuthNone       AuthKind = "none"
	AuthSession    AuthKind = "session"
	AuthPermission AuthKind = "permission"
)

// OperationAuth 是单个接口的鉴权规则。
type OperationAuth struct {
	Kind       AuthKind
	Permission string
	Access     string
}

// OperationAuths 的键是 strict 中间件收到的 operationID（首字母大写的 operationId）。
var OperationAuths = map[string]OperationAuth{
	"AdminGetMe":  {Kind: AuthSession},
	"AdminLogin":  {Kind: AuthNone},
	"AdminLogout": {Kind: AuthSession},
	"GetHealthz":  {Kind: AuthNone},
	"GetReadyz":   {Kind: AuthNone},
}
