// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runner.sql

package store

import (
	"context"
	"net/netip"
	"time"
)

const getUserSession = `-- name: GetUserSession :one
SELECT s.expires_at,
       s.revoked_at,
       u.id AS user_id,
       u.telegram_user_id,
       u.telegram_username,
       u.display_name,
       u.locale,
       u.status
FROM sessions s
JOIN users u ON u.id = s.subject_id
WHERE s.subject_type = 'USER'
  AND s.token_hash = $1
`

type GetUserSessionRow struct {
	ExpiresAt        time.Time
	RevokedAt        *time.Time
	UserID           int64
	TelegramUserID   *int64
	TelegramUsername *string
	DisplayName      *string
	Locale           string
	Status           string
}

func (q *Queries) GetUserSession(ctx context.Context, tokenHash []byte) (GetUserSessionRow, error) {
	row := q.db.QueryRow(ctx, getUserSession, tokenHash)
	var i GetUserSessionRow
	err := row.Scan(
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.UserID,
		&i.TelegramUserID,
		&i.TelegramUsername,
		&i.DisplayName,
		&i.Locale,
		&i.Status,
	)
	return i, err
}

const insertUserSession = `-- name: InsertUserSession :exec
INSERT INTO sessions (subject_type, subject_id, token_hash, expires_at, ip, user_agent, created_at)
VALUES ('USER', $1, $2, $3, $4, $5, $6)
`

type InsertUserSessionParams struct {
	UserID    int64
	TokenHash []byte
	ExpiresAt time.Time
	Ip        *netip.Addr
	UserAgent *string
	CreatedAt time.Time
}

func (q *Queries) InsertUserSession(ctx context.Context, arg InsertUserSessionParams) error {
	_, err := q.db.Exec(ctx, insertUserSession,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.Ip,
		arg.UserAgent,
		arg.CreatedAt,
	)
	return err
}

const revokeUserSession = `-- name: RevokeUserSession :exec
UPDATE sessions SET revoked_at = $1::timestamptz
WHERE subject_type = 'USER' AND token_hash = $2 AND revoked_at IS NULL
`

type RevokeUserSessionParams struct {
	RevokedAt time.Time
	TokenHash []byte
}

func (q *Queries) RevokeUserSession(ctx context.Context, arg RevokeUserSessionParams) error {
	_, err := q.db.Exec(ctx, revokeUserSession, arg.RevokedAt, arg.TokenHash)
	return err
}

const upsertTelegramUser = `-- name: UpsertTelegramUser :one
INSERT INTO users (telegram_user_id, telegram_username, display_name, locale, last_login_at)
VALUES ($1::bigint, $2, $3, $4, $5::timestamptz)
ON CONFLICT (telegram_user_id) DO UPDATE
SET telegram_username = EXCLUDED.telegram_username,
    display_name      = EXCLUDED.display_name,
    last_login_at     = EXCLUDED.last_login_at
RETURNING id, telegram_user_id, telegram_username, display_name, locale, status
`

type UpsertTelegramUserParams struct {
	TelegramUserID   int64
	TelegramUsername *string
	DisplayName      *string
	Locale           string
	LastLoginAt      time.Time
}

type UpsertTelegramUserRow struct {
	ID               int64
	TelegramUserID   *int64
	TelegramUsername *string
	DisplayName      *string
	Locale           string
	Status           string
}

// 首次登录创建跑者；再次登录只更新用户名、显示名与最近登录时间，不覆盖 locale。
func (q *Queries) UpsertTelegramUser(ctx context.Context, arg UpsertTelegramUserParams) (UpsertTelegramUserRow, error) {
	row := q.db.QueryRow(ctx, upsertTelegramUser,
		arg.TelegramUserID,
		arg.TelegramUsername,
		arg.DisplayName,
		arg.Locale,
		arg.LastLoginAt,
	)
	var i UpsertTelegramUserRow
	err := row.Scan(
		&i.ID,
		&i.TelegramUserID,
		&i.TelegramUsername,
		&i.DisplayName,
		&i.Locale,
		&i.Status,
	)
	return i, err
}
