// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runner.sql

package store

import (
	"context"
	"net/netip"
	"time"
)

const clearSelfProfiles = `-- name: ClearSelfProfiles :exec
UPDATE runner_profiles SET is_self = false
WHERE user_id = $1 AND is_self AND id <> $2
`

type ClearSelfProfilesParams struct {
	UserID   int64
	ExceptID int64
}

func (q *Queries) ClearSelfProfiles(ctx context.Context, arg ClearSelfProfilesParams) error {
	_, err := q.db.Exec(ctx, clearSelfProfiles, arg.UserID, arg.ExceptID)
	return err
}

const deleteProfile = `-- name: DeleteProfile :execrows
DELETE FROM runner_profiles WHERE id = $1 AND user_id = $2
`

type DeleteProfileParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteProfile(ctx context.Context, arg DeleteProfileParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProfile, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getConsentVersion = `-- name: GetConsentVersion :one
SELECT version, lang, purpose, items, text_sha256
FROM disclaimer_versions
WHERE version = $1 AND lang = $2
`

type GetConsentVersionParams struct {
	Version string
	Lang    string
}

type GetConsentVersionRow struct {
	Version    string
	Lang       string
	Purpose    string
	Items      []byte
	TextSha256 []byte
}

func (q *Queries) GetConsentVersion(ctx context.Context, arg GetConsentVersionParams) (GetConsentVersionRow, error) {
	row := q.db.QueryRow(ctx, getConsentVersion, arg.Version, arg.Lang)
	var i GetConsentVersionRow
	err := row.Scan(
		&i.Version,
		&i.Lang,
		&i.Purpose,
		&i.Items,
		&i.TextSha256,
	)
	return i, err
}

const getCurrentConsent = `-- name: GetCurrentConsent :one
SELECT version, lang, effective_date, full_text, items
FROM disclaimer_versions
WHERE purpose = $1
  AND lang = $2
  AND effective_date <= $3::date
ORDER BY effective_date DESC, created_at DESC, version DESC
LIMIT 1
`

type GetCurrentConsentParams struct {
	Purpose string
	Lang    string
	Today   time.Time
}

type GetCurrentConsentRow struct {
	Version       string
	Lang          string
	EffectiveDate time.Time
	FullText      string
	Items         []byte
}

func (q *Queries) GetCurrentConsent(ctx context.Context, arg GetCurrentConsentParams) (GetCurrentConsentRow, error) {
	row := q.db.QueryRow(ctx, getCurrentConsent, arg.Purpose, arg.Lang, arg.Today)
	var i GetCurrentConsentRow
	err := row.Scan(
		&i.Version,
		&i.Lang,
		&i.EffectiveDate,
		&i.FullText,
		&i.Items,
	)
	return i, err
}

const getProfile = `-- name: GetProfile :one
SELECT id, user_id, full_name, gender, birth_date, nationality, id_type, id_no_enc, id_no_hash, phone_e164, email, emergency_name, emergency_phone, tshirt_size, is_self, created_at, updated_at FROM runner_profiles
WHERE id = $1 AND user_id = $2
`

type GetProfileParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetProfile(ctx context.Context, arg GetProfileParams) (RunnerProfile, error) {
	row := q.db.QueryRow(ctx, getProfile, arg.ID, arg.UserID)
	var i RunnerProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FullName,
		&i.Gender,
		&i.BirthDate,
		&i.Nationality,
		&i.IDType,
		&i.IDNoEnc,
		&i.IDNoHash,
		&i.PhoneE164,
		&i.Email,
		&i.EmergencyName,
		&i.EmergencyPhone,
		&i.TshirtSize,
		&i.IsSelf,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProfileForUpdate = `-- name: GetProfileForUpdate :one
SELECT id, user_id, full_name, gender, birth_date, nationality, id_type, id_no_enc, id_no_hash, phone_e164, email, emergency_name, emergency_phone, tshirt_size, is_self, created_at, updated_at FROM runner_profiles
WHERE id = $1 AND user_id = $2
FOR UPDATE
`

type GetProfileForUpdateParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetProfileForUpdate(ctx context.Context, arg GetProfileForUpdateParams) (RunnerProfile, error) {
	row := q.db.QueryRow(ctx, getProfileForUpdate, arg.ID, arg.UserID)
	var i RunnerProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FullName,
		&i.Gender,
		&i.BirthDate,
		&i.Nationality,
		&i.IDType,
		&i.IDNoEnc,
		&i.IDNoHash,
		&i.PhoneE164,
		&i.Email,
		&i.EmergencyName,
		&i.EmergencyPhone,
		&i.TshirtSize,
		&i.IsSelf,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserSession = `-- name: GetUserSession :one
SELECT s.expires_at,
       s.revoked_at,
       u.id AS user_id,
       u.telegram_user_id,
       u.telegram_username,
       u.display_name,
       u.locale,
       u.status
FROM sessions s
JOIN users u ON u.id = s.subject_id
WHERE s.subject_type = 'USER'
  AND s.token_hash = $1
`

type GetUserSessionRow struct {
	ExpiresAt        time.Time
	RevokedAt        *time.Time
	UserID           int64
	TelegramUserID   *int64
	TelegramUsername *string
	DisplayName      *string
	Locale           string
	Status           string
}

func (q *Queries) GetUserSession(ctx context.Context, tokenHash []byte) (GetUserSessionRow, error) {
	row := q.db.QueryRow(ctx, getUserSession, tokenHash)
	var i GetUserSessionRow
	err := row.Scan(
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.UserID,
		&i.TelegramUserID,
		&i.TelegramUsername,
		&i.DisplayName,
		&i.Locale,
		&i.Status,
	)
	return i, err
}

const insertConsentSignature = `-- name: InsertConsentSignature :one
INSERT INTO disclaimer_signatures (version, lang, text_sha256, user_id, checked_items, signed_at, ip, user_agent)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id
`

type InsertConsentSignatureParams struct {
	Version      string
	Lang         string
	TextSha256   []byte
	UserID       int64
	CheckedItems []byte
	SignedAt     time.Time
	Ip           *netip.Addr
	UserAgent    *string
}

func (q *Queries) InsertConsentSignature(ctx context.Context, arg InsertConsentSignatureParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertConsentSignature,
		arg.Version,
		arg.Lang,
		arg.TextSha256,
		arg.UserID,
		arg.CheckedItems,
		arg.SignedAt,
		arg.Ip,
		arg.UserAgent,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertConsentVersion = `-- name: InsertConsentVersion :exec
INSERT INTO disclaimer_versions (version, lang, effective_date, full_text, items, text_sha256, purpose)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertConsentVersionParams struct {
	Version       string
	Lang          string
	EffectiveDate time.Time
	FullText      string
	Items         []byte
	TextSha256    []byte
	Purpose       string
}

func (q *Queries) InsertConsentVersion(ctx context.Context, arg InsertConsentVersionParams) error {
	_, err := q.db.Exec(ctx, insertConsentVersion,
		arg.Version,
		arg.Lang,
		arg.EffectiveDate,
		arg.FullText,
		arg.Items,
		arg.TextSha256,
		arg.Purpose,
	)
	return err
}

const insertProfile = `-- name: InsertProfile :one
INSERT INTO runner_profiles (
  user_id, full_name, gender, birth_date, nationality, id_type, id_no_enc, id_no_hash,
  phone_e164, email, emergency_name, emergency_phone, tshirt_size, is_self
) VALUES (
  $1, $2, $3, $4, $5, $6::text, $7::bytea, $8::bytea,
  $9::text, $10, $11::text, $12::text, $13::text, $14
)
RETURNING id, user_id, full_name, gender, birth_date, nationality, id_type, id_no_enc, id_no_hash, phone_e164, email, emergency_name, emergency_phone, tshirt_size, is_self, created_at, updated_at
`

type InsertProfileParams struct {
	UserID         int64
	FullName       string
	Gender         string
	BirthDate      time.Time
	Nationality    string
	IDType         string
	IDNoEnc        []byte
	IDNoHash       []byte
	PhoneE164      string
	Email          *string
	EmergencyName  string
	EmergencyPhone string
	TshirtSize     string
	IsSelf         bool
}

func (q *Queries) InsertProfile(ctx context.Context, arg InsertProfileParams) (RunnerProfile, error) {
	row := q.db.QueryRow(ctx, insertProfile,
		arg.UserID,
		arg.FullName,
		arg.Gender,
		arg.BirthDate,
		arg.Nationality,
		arg.IDType,
		arg.IDNoEnc,
		arg.IDNoHash,
		arg.PhoneE164,
		arg.Email,
		arg.EmergencyName,
		arg.EmergencyPhone,
		arg.TshirtSize,
		arg.IsSelf,
	)
	var i RunnerProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FullName,
		&i.Gender,
		&i.BirthDate,
		&i.Nationality,
		&i.IDType,
		&i.IDNoEnc,
		&i.IDNoHash,
		&i.PhoneE164,
		&i.Email,
		&i.EmergencyName,
		&i.EmergencyPhone,
		&i.TshirtSize,
		&i.IsSelf,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertRegistrationConsent = `-- name: InsertRegistrationConsent :exec
INSERT INTO registration_consents (signature_id, reg_order_id, free_signup_id)
VALUES ($1, $2, $3)
`

type InsertRegistrationConsentParams struct {
	SignatureID  int64
	RegOrderID   *int64
	FreeSignupID *int64
}

func (q *Queries) InsertRegistrationConsent(ctx context.Context, arg InsertRegistrationConsentParams) error {
	_, err := q.db.Exec(ctx, insertRegistrationConsent, arg.SignatureID, arg.RegOrderID, arg.FreeSignupID)
	return err
}

const insertUserSession = `-- name: InsertUserSession :exec
INSERT INTO sessions (subject_type, subject_id, token_hash, expires_at, ip, user_agent, created_at)
VALUES ('USER', $1, $2, $3, $4, $5, $6)
`

type InsertUserSessionParams struct {
	UserID    int64
	TokenHash []byte
	ExpiresAt time.Time
	Ip        *netip.Addr
	UserAgent *string
	CreatedAt time.Time
}

func (q *Queries) InsertUserSession(ctx context.Context, arg InsertUserSessionParams) error {
	_, err := q.db.Exec(ctx, insertUserSession,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.Ip,
		arg.UserAgent,
		arg.CreatedAt,
	)
	return err
}

const listProfiles = `-- name: ListProfiles :many
SELECT id, user_id, full_name, gender, birth_date, nationality, id_type, id_no_enc, id_no_hash, phone_e164, email, emergency_name, emergency_phone, tshirt_size, is_self, created_at, updated_at FROM runner_profiles
WHERE user_id = $1
ORDER BY is_self DESC, id
`

func (q *Queries) ListProfiles(ctx context.Context, userID int64) ([]RunnerProfile, error) {
	rows, err := q.db.Query(ctx, listProfiles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RunnerProfile
	for rows.Next() {
		var i RunnerProfile
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FullName,
			&i.Gender,
			&i.BirthDate,
			&i.Nationality,
			&i.IDType,
			&i.IDNoEnc,
			&i.IDNoHash,
			&i.PhoneE164,
			&i.Email,
			&i.EmergencyName,
			&i.EmergencyPhone,
			&i.TshirtSize,
			&i.IsSelf,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockUser = `-- name: LockUser :one
SELECT id FROM users WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockUser(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, lockUser, id)
	var id_2 int64
	err := row.Scan(&id_2)
	return id_2, err
}

const revokeUserSession = `-- name: RevokeUserSession :exec
UPDATE sessions SET revoked_at = $1::timestamptz
WHERE subject_type = 'USER' AND token_hash = $2 AND revoked_at IS NULL
`

type RevokeUserSessionParams struct {
	RevokedAt time.Time
	TokenHash []byte
}

func (q *Queries) RevokeUserSession(ctx context.Context, arg RevokeUserSessionParams) error {
	_, err := q.db.Exec(ctx, revokeUserSession, arg.RevokedAt, arg.TokenHash)
	return err
}

const updateProfile = `-- name: UpdateProfile :one
UPDATE runner_profiles
SET full_name       = $1,
    gender          = $2,
    birth_date      = $3,
    nationality     = $4,
    id_type         = $5::text,
    id_no_enc       = $6::bytea,
    id_no_hash      = $7::bytea,
    phone_e164      = $8::text,
    email           = $9,
    emergency_name  = $10::text,
    emergency_phone = $11::text,
    tshirt_size     = $12::text,
    is_self         = $13
WHERE id = $14 AND user_id = $15
RETURNING id, user_id, full_name, gender, birth_date, nationality, id_type, id_no_enc, id_no_hash, phone_e164, email, emergency_name, emergency_phone, tshirt_size, is_self, created_at, updated_at
`

type UpdateProfileParams struct {
	FullName       string
	Gender         string
	BirthDate      time.Time
	Nationality    string
	IDType         string
	IDNoEnc        []byte
	IDNoHash       []byte
	PhoneE164      string
	Email          *string
	EmergencyName  string
	EmergencyPhone string
	TshirtSize     string
	IsSelf         bool
	ID             int64
	UserID         int64
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) (RunnerProfile, error) {
	row := q.db.QueryRow(ctx, updateProfile,
		arg.FullName,
		arg.Gender,
		arg.BirthDate,
		arg.Nationality,
		arg.IDType,
		arg.IDNoEnc,
		arg.IDNoHash,
		arg.PhoneE164,
		arg.Email,
		arg.EmergencyName,
		arg.EmergencyPhone,
		arg.TshirtSize,
		arg.IsSelf,
		arg.ID,
		arg.UserID,
	)
	var i RunnerProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FullName,
		&i.Gender,
		&i.BirthDate,
		&i.Nationality,
		&i.IDType,
		&i.IDNoEnc,
		&i.IDNoHash,
		&i.PhoneE164,
		&i.Email,
		&i.EmergencyName,
		&i.EmergencyPhone,
		&i.TshirtSize,
		&i.IsSelf,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTelegramUser = `-- name: UpsertTelegramUser :one
INSERT INTO users (telegram_user_id, telegram_username, display_name, locale, last_login_at)
VALUES ($1::bigint, $2, $3, $4, $5::timestamptz)
ON CONFLICT (telegram_user_id) DO UPDATE
SET telegram_username = EXCLUDED.telegram_username,
    display_name      = EXCLUDED.display_name,
    last_login_at     = EXCLUDED.last_login_at
RETURNING id, telegram_user_id, telegram_username, display_name, locale, status
`

type UpsertTelegramUserParams struct {
	TelegramUserID   int64
	TelegramUsername *string
	DisplayName      *string
	Locale           string
	LastLoginAt      time.Time
}

type UpsertTelegramUserRow struct {
	ID               int64
	TelegramUserID   *int64
	TelegramUsername *string
	DisplayName      *string
	Locale           string
	Status           string
}

// 首次登录创建跑者；再次登录只更新用户名、显示名与最近登录时间，不覆盖 locale。
func (q *Queries) UpsertTelegramUser(ctx context.Context, arg UpsertTelegramUserParams) (UpsertTelegramUserRow, error) {
	row := q.db.QueryRow(ctx, upsertTelegramUser,
		arg.TelegramUserID,
		arg.TelegramUsername,
		arg.DisplayName,
		arg.Locale,
		arg.LastLoginAt,
	)
	var i UpsertTelegramUserRow
	err := row.Scan(
		&i.ID,
		&i.TelegramUserID,
		&i.TelegramUsername,
		&i.DisplayName,
		&i.Locale,
		&i.Status,
	)
	return i, err
}
