// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event.sql

package store

import (
	"context"
	"time"
)

const getEventForUpdate = `-- name: GetEventForUpdate :one
SELECT id, slug, event_type, organizer_type, name, summary, description, city, venue, race_date, timezone, cover_file_id, status, registration_open, public_visible, registration_opens_at, registration_closes_at, race_pack_configured, community_review_required, activity_info, published_at, published_by, created_by, version, created_at, updated_at FROM events
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetEventForUpdate(ctx context.Context, id int64) (Event, error) {
	row := q.db.QueryRow(ctx, getEventForUpdate, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.EventType,
		&i.OrganizerType,
		&i.Name,
		&i.Summary,
		&i.Description,
		&i.City,
		&i.Venue,
		&i.RaceDate,
		&i.Timezone,
		&i.CoverFileID,
		&i.Status,
		&i.RegistrationOpen,
		&i.PublicVisible,
		&i.RegistrationOpensAt,
		&i.RegistrationClosesAt,
		&i.RacePackConfigured,
		&i.CommunityReviewRequired,
		&i.ActivityInfo,
		&i.PublishedAt,
		&i.PublishedBy,
		&i.CreatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublicEventBySlug = `-- name: GetPublicEventBySlug :one
SELECT id, slug, event_type, organizer_type, name, summary, description, city, venue, race_date, timezone, cover_file_id, status, registration_open, public_visible, registration_opens_at, registration_closes_at, race_pack_configured, community_review_required, activity_info, published_at, published_by, created_by, version, created_at, updated_at FROM events
WHERE slug = $1 AND status = 'PUBLISHED' AND public_visible
`

func (q *Queries) GetPublicEventBySlug(ctx context.Context, slug string) (Event, error) {
	row := q.db.QueryRow(ctx, getPublicEventBySlug, slug)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.EventType,
		&i.OrganizerType,
		&i.Name,
		&i.Summary,
		&i.Description,
		&i.City,
		&i.Venue,
		&i.RaceDate,
		&i.Timezone,
		&i.CoverFileID,
		&i.Status,
		&i.RegistrationOpen,
		&i.PublicVisible,
		&i.RegistrationOpensAt,
		&i.RegistrationClosesAt,
		&i.RacePackConfigured,
		&i.CommunityReviewRequired,
		&i.ActivityInfo,
		&i.PublishedAt,
		&i.PublishedBy,
		&i.CreatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCategory = `-- name: InsertCategory :one
INSERT INTO event_categories (event_id, code, name, distance_m, capacity, start_at, cutoff_at, sort_order)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, event_id, code, name, distance_m, capacity, used_count, reserved_count, start_at, cutoff_at, min_age, sort_order, created_at, updated_at
`

type InsertCategoryParams struct {
	EventID   int64
	Code      string
	Name      []byte
	DistanceM int32
	Capacity  int32
	StartAt   *time.Time
	CutoffAt  *time.Time
	SortOrder int16
}

func (q *Queries) InsertCategory(ctx context.Context, arg InsertCategoryParams) (EventCategory, error) {
	row := q.db.QueryRow(ctx, insertCategory,
		arg.EventID,
		arg.Code,
		arg.Name,
		arg.DistanceM,
		arg.Capacity,
		arg.StartAt,
		arg.CutoffAt,
		arg.SortOrder,
	)
	var i EventCategory
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Code,
		&i.Name,
		&i.DistanceM,
		&i.Capacity,
		&i.UsedCount,
		&i.ReservedCount,
		&i.StartAt,
		&i.CutoffAt,
		&i.MinAge,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertEvent = `-- name: InsertEvent :one
INSERT INTO events (slug, event_type, organizer_type, name, city, race_date, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, slug, event_type, organizer_type, name, summary, description, city, venue, race_date, timezone, cover_file_id, status, registration_open, public_visible, registration_opens_at, registration_closes_at, race_pack_configured, community_review_required, activity_info, published_at, published_by, created_by, version, created_at, updated_at
`

type InsertEventParams struct {
	Slug          string
	EventType     string
	OrganizerType string
	Name          []byte
	City          string
	RaceDate      time.Time
	CreatedBy     *int64
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, insertEvent,
		arg.Slug,
		arg.EventType,
		arg.OrganizerType,
		arg.Name,
		arg.City,
		arg.RaceDate,
		arg.CreatedBy,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.EventType,
		&i.OrganizerType,
		&i.Name,
		&i.Summary,
		&i.Description,
		&i.City,
		&i.Venue,
		&i.RaceDate,
		&i.Timezone,
		&i.CoverFileID,
		&i.Status,
		&i.RegistrationOpen,
		&i.PublicVisible,
		&i.RegistrationOpensAt,
		&i.RegistrationClosesAt,
		&i.RacePackConfigured,
		&i.CommunityReviewRequired,
		&i.ActivityInfo,
		&i.PublishedAt,
		&i.PublishedBy,
		&i.CreatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCategoriesByEventIDs = `-- name: ListCategoriesByEventIDs :many
SELECT id, event_id, code, name, distance_m, capacity, used_count, reserved_count, start_at, cutoff_at, min_age, sort_order, created_at, updated_at FROM event_categories
WHERE event_id = ANY($1::bigint[])
ORDER BY event_id, sort_order, id
`

func (q *Queries) ListCategoriesByEventIDs(ctx context.Context, eventIds []int64) ([]EventCategory, error) {
	rows, err := q.db.Query(ctx, listCategoriesByEventIDs, eventIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventCategory
	for rows.Next() {
		var i EventCategory
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Code,
			&i.Name,
			&i.DistanceM,
			&i.Capacity,
			&i.UsedCount,
			&i.ReservedCount,
			&i.StartAt,
			&i.CutoffAt,
			&i.MinAge,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvents = `-- name: ListEvents :many
SELECT id, slug, event_type, organizer_type, name, summary, description, city, venue, race_date, timezone, cover_file_id, status, registration_open, public_visible, registration_opens_at, registration_closes_at, race_pack_configured, community_review_required, activity_info, published_at, published_by, created_by, version, created_at, updated_at FROM events
ORDER BY race_date DESC, id DESC
`

func (q *Queries) ListEvents(ctx context.Context) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.EventType,
			&i.OrganizerType,
			&i.Name,
			&i.Summary,
			&i.Description,
			&i.City,
			&i.Venue,
			&i.RaceDate,
			&i.Timezone,
			&i.CoverFileID,
			&i.Status,
			&i.RegistrationOpen,
			&i.PublicVisible,
			&i.RegistrationOpensAt,
			&i.RegistrationClosesAt,
			&i.RacePackConfigured,
			&i.CommunityReviewRequired,
			&i.ActivityInfo,
			&i.PublishedAt,
			&i.PublishedBy,
			&i.CreatedBy,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicEvents = `-- name: ListPublicEvents :many
SELECT id, slug, event_type, organizer_type, name, summary, description, city, venue, race_date, timezone, cover_file_id, status, registration_open, public_visible, registration_opens_at, registration_closes_at, race_pack_configured, community_review_required, activity_info, published_at, published_by, created_by, version, created_at, updated_at FROM events
WHERE status = 'PUBLISHED' AND public_visible
ORDER BY race_date, id
`

func (q *Queries) ListPublicEvents(ctx context.Context) ([]Event, error) {
	rows, err := q.db.Query(ctx, listPublicEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.EventType,
			&i.OrganizerType,
			&i.Name,
			&i.Summary,
			&i.Description,
			&i.City,
			&i.Venue,
			&i.RaceDate,
			&i.Timezone,
			&i.CoverFileID,
			&i.Status,
			&i.RegistrationOpen,
			&i.PublicVisible,
			&i.RegistrationOpensAt,
			&i.RegistrationClosesAt,
			&i.RacePackConfigured,
			&i.CommunityReviewRequired,
			&i.ActivityInfo,
			&i.PublishedAt,
			&i.PublishedBy,
			&i.CreatedBy,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishEvent = `-- name: PublishEvent :one
UPDATE events
SET status = 'PUBLISHED',
    public_visible = true,
    published_at = $1,
    published_by = $2,
    version = version + 1
WHERE id = $3
RETURNING id, slug, event_type, organizer_type, name, summary, description, city, venue, race_date, timezone, cover_file_id, status, registration_open, public_visible, registration_opens_at, registration_closes_at, race_pack_configured, community_review_required, activity_info, published_at, published_by, created_by, version, created_at, updated_at
`

type PublishEventParams struct {
	PublishedAt *time.Time
	PublishedBy *int64
	ID          int64
}

func (q *Queries) PublishEvent(ctx context.Context, arg PublishEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, publishEvent, arg.PublishedAt, arg.PublishedBy, arg.ID)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.EventType,
		&i.OrganizerType,
		&i.Name,
		&i.Summary,
		&i.Description,
		&i.City,
		&i.Venue,
		&i.RaceDate,
		&i.Timezone,
		&i.CoverFileID,
		&i.Status,
		&i.RegistrationOpen,
		&i.PublicVisible,
		&i.RegistrationOpensAt,
		&i.RegistrationClosesAt,
		&i.RacePackConfigured,
		&i.CommunityReviewRequired,
		&i.ActivityInfo,
		&i.PublishedAt,
		&i.PublishedBy,
		&i.CreatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
