// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: storage.sql

package store

import (
	"context"
)

const countOtherFilesWithSHA256 = `-- name: CountOtherFilesWithSHA256 :one
SELECT count(*) FROM files
WHERE sha256 = $1 AND purpose = $2 AND id <> $3
`

type CountOtherFilesWithSHA256Params struct {
	Sha256    []byte
	Purpose   string
	ExcludeID int64
}

func (q *Queries) CountOtherFilesWithSHA256(ctx context.Context, arg CountOtherFilesWithSHA256Params) (int64, error) {
	row := q.db.QueryRow(ctx, countOtherFilesWithSHA256, arg.Sha256, arg.Purpose, arg.ExcludeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getFile = `-- name: GetFile :one
SELECT id, storage_key, visibility, mime_type, size_bytes, sha256
FROM files
WHERE id = $1
`

type GetFileRow struct {
	ID         int64
	StorageKey string
	Visibility string
	MimeType   string
	SizeBytes  int64
	Sha256     []byte
}

func (q *Queries) GetFile(ctx context.Context, id int64) (GetFileRow, error) {
	row := q.db.QueryRow(ctx, getFile, id)
	var i GetFileRow
	err := row.Scan(
		&i.ID,
		&i.StorageKey,
		&i.Visibility,
		&i.MimeType,
		&i.SizeBytes,
		&i.Sha256,
	)
	return i, err
}

const insertFile = `-- name: InsertFile :one
INSERT INTO files (storage_key, visibility, purpose, mime_type, size_bytes, sha256,
                   width, height, uploaded_by_type, uploaded_by_id)
VALUES ($1, $2, $3, $4, $5, $6,
        $7, $8, $9, $10)
RETURNING id
`

type InsertFileParams struct {
	StorageKey     string
	Visibility     string
	Purpose        string
	MimeType       string
	SizeBytes      int64
	Sha256         []byte
	Width          *int32
	Height         *int32
	UploadedByType string
	UploadedByID   *int64
}

func (q *Queries) InsertFile(ctx context.Context, arg InsertFileParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertFile,
		arg.StorageKey,
		arg.Visibility,
		arg.Purpose,
		arg.MimeType,
		arg.SizeBytes,
		arg.Sha256,
		arg.Width,
		arg.Height,
		arg.UploadedByType,
		arg.UploadedByID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
