// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pricing.sql

package store

import (
	"context"
	"time"
)

const deleteCategoryLinksByRule = `-- name: DeleteCategoryLinksByRule :exec
DELETE FROM category_price_rules
WHERE price_rule_id = $1
`

func (q *Queries) DeleteCategoryLinksByRule(ctx context.Context, priceRuleID int64) error {
	_, err := q.db.Exec(ctx, deleteCategoryLinksByRule, priceRuleID)
	return err
}

const eventExists = `-- name: EventExists :one
SELECT EXISTS (SELECT 1 FROM events WHERE id = $1)
`

func (q *Queries) EventExists(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, eventExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getPriceRuleForUpdate = `-- name: GetPriceRuleForUpdate :one
SELECT id, event_id, name, audience, price_cents, currency, quota, used_count, reserved_count, sale_starts_at, sale_ends_at, sort_order, created_at, updated_at FROM price_rules
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetPriceRuleForUpdate(ctx context.Context, id int64) (PriceRule, error) {
	row := q.db.QueryRow(ctx, getPriceRuleForUpdate, id)
	var i PriceRule
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.Audience,
		&i.PriceCents,
		&i.Currency,
		&i.Quota,
		&i.UsedCount,
		&i.ReservedCount,
		&i.SaleStartsAt,
		&i.SaleEndsAt,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCategoryLink = `-- name: InsertCategoryLink :exec
INSERT INTO category_price_rules (category_id, price_rule_id)
VALUES ($1, $2)
`

type InsertCategoryLinkParams struct {
	CategoryID  int64
	PriceRuleID int64
}

func (q *Queries) InsertCategoryLink(ctx context.Context, arg InsertCategoryLinkParams) error {
	_, err := q.db.Exec(ctx, insertCategoryLink, arg.CategoryID, arg.PriceRuleID)
	return err
}

const insertPriceRule = `-- name: InsertPriceRule :one
INSERT INTO price_rules (event_id, name, audience, price_cents, currency, quota, sale_starts_at, sale_ends_at, sort_order)
VALUES ($1, $2, $3, $4, 'USD', $5, $6,
        $7, $8)
RETURNING id, event_id, name, audience, price_cents, currency, quota, used_count, reserved_count, sale_starts_at, sale_ends_at, sort_order, created_at, updated_at
`

type InsertPriceRuleParams struct {
	EventID      int64
	Name         []byte
	Audience     string
	PriceCents   int64
	Quota        *int32
	SaleStartsAt *time.Time
	SaleEndsAt   *time.Time
	SortOrder    int16
}

func (q *Queries) InsertPriceRule(ctx context.Context, arg InsertPriceRuleParams) (PriceRule, error) {
	row := q.db.QueryRow(ctx, insertPriceRule,
		arg.EventID,
		arg.Name,
		arg.Audience,
		arg.PriceCents,
		arg.Quota,
		arg.SaleStartsAt,
		arg.SaleEndsAt,
		arg.SortOrder,
	)
	var i PriceRule
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.Audience,
		&i.PriceCents,
		&i.Currency,
		&i.Quota,
		&i.UsedCount,
		&i.ReservedCount,
		&i.SaleStartsAt,
		&i.SaleEndsAt,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCategoryIDsOfEvent = `-- name: ListCategoryIDsOfEvent :many
SELECT id FROM event_categories
WHERE event_id = $1
ORDER BY id
`

func (q *Queries) ListCategoryIDsOfEvent(ctx context.Context, eventID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listCategoryIDsOfEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoryLinksByRuleIDs = `-- name: ListCategoryLinksByRuleIDs :many
SELECT category_id, price_rule_id FROM category_price_rules
WHERE price_rule_id = ANY($1::bigint[])
ORDER BY price_rule_id, category_id
`

func (q *Queries) ListCategoryLinksByRuleIDs(ctx context.Context, ruleIds []int64) ([]CategoryPriceRule, error) {
	rows, err := q.db.Query(ctx, listCategoryLinksByRuleIDs, ruleIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CategoryPriceRule
	for rows.Next() {
		var i CategoryPriceRule
		if err := rows.Scan(&i.CategoryID, &i.PriceRuleID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPriceRulesByEvent = `-- name: ListPriceRulesByEvent :many
SELECT id, event_id, name, audience, price_cents, currency, quota, used_count, reserved_count, sale_starts_at, sale_ends_at, sort_order, created_at, updated_at FROM price_rules
WHERE event_id = $1
ORDER BY sort_order, id
`

func (q *Queries) ListPriceRulesByEvent(ctx context.Context, eventID int64) ([]PriceRule, error) {
	rows, err := q.db.Query(ctx, listPriceRulesByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PriceRule
	for rows.Next() {
		var i PriceRule
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Name,
			&i.Audience,
			&i.PriceCents,
			&i.Currency,
			&i.Quota,
			&i.UsedCount,
			&i.ReservedCount,
			&i.SaleStartsAt,
			&i.SaleEndsAt,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePriceRule = `-- name: UpdatePriceRule :one
UPDATE price_rules
SET name = $1,
    audience = $2,
    price_cents = $3,
    quota = $4,
    sale_starts_at = $5,
    sale_ends_at = $6,
    sort_order = $7,
    updated_at = now()
WHERE id = $8
RETURNING id, event_id, name, audience, price_cents, currency, quota, used_count, reserved_count, sale_starts_at, sale_ends_at, sort_order, created_at, updated_at
`

type UpdatePriceRuleParams struct {
	Name         []byte
	Audience     string
	PriceCents   int64
	Quota        *int32
	SaleStartsAt *time.Time
	SaleEndsAt   *time.Time
	SortOrder    int16
	ID           int64
}

func (q *Queries) UpdatePriceRule(ctx context.Context, arg UpdatePriceRuleParams) (PriceRule, error) {
	row := q.db.QueryRow(ctx, updatePriceRule,
		arg.Name,
		arg.Audience,
		arg.PriceCents,
		arg.Quota,
		arg.SaleStartsAt,
		arg.SaleEndsAt,
		arg.SortOrder,
		arg.ID,
	)
	var i PriceRule
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.Audience,
		&i.PriceCents,
		&i.Currency,
		&i.Quota,
		&i.UsedCount,
		&i.ReservedCount,
		&i.SaleStartsAt,
		&i.SaleEndsAt,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
