/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 进程存活检查 */
        get: operations["getHealthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 数据库连通检查 */
        get: operations["getReadyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 员工登录 */
        post: operations["adminLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 退出登录 */
        post: operations["adminLogout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 当前员工与权限 */
        get: operations["adminGetMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 已发布且公开展示的赛事列表，文案按请求语言返回 */
        get: operations["listPublicEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 赛事详情（含组别） */
        get: operations["getPublicEvent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 后台赛事列表（名称返回三语） */
        get: operations["adminListEvents"];
        put?: never;
        /** 新建草稿赛事及组别 */
        post: operations["adminCreateEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/events/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 后台赛事详情（任意状态，含报名设置与组别） */
        get: operations["adminGetEvent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/events/{id}/registration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 修改报名开关与报名时间（开放前校验发布状态、价格档与收款账户） */
        patch: operations["adminUpdateEventRegistration"];
        trace?: never;
    };
    "/admin/events/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 发布赛事（发布前校验） */
        post: operations["adminPublishEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/events/{id}/price-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 赛事的价格档列表（含关联组别与计数） */
        get: operations["adminListPriceRules"];
        put?: never;
        /** 新建价格档 */
        post: operations["adminCreatePriceRule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/price-rules/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 修改价格档（已有占用时不可改价格、人群、关联组别） */
        put: operations["adminUpdatePriceRule"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/coupons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 优惠码列表（eventId 为空时返回全部） */
        get: operations["adminListCoupons"];
        put?: never;
        /** 新建优惠码（代码自动转大写） */
        post: operations["adminCreateCoupon"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/coupons/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 修改优惠码（代码不可改） */
        put: operations["adminUpdateCoupon"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 公开文件（收款二维码）；私有或不存在返回 404；响应头 Cache-Control public, max-age=86400 */
        get: operations["getPublicFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/payment-accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 收款账户列表 */
        get: operations["adminListPaymentAccounts"];
        put?: never;
        /** 新建收款账户（上传二维码，币种固定 USD） */
        post: operations["adminCreatePaymentAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/payment-accounts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 修改收款账户（带 qr 时更换二维码，旧文件保留） */
        put: operations["adminUpdatePaymentAccount"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/app/auth/telegram": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 用 Telegram 小程序 initData 登录，返回跑者令牌 */
        post: operations["appLoginTelegram"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/app/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 吊销当前跑者令牌 */
        post: operations["appLogout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/app/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 当前跑者 */
        get: operations["appGetMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/app/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 当前跑者的常用参赛人（证件号只返回后 4 位） */
        get: operations["appListProfiles"];
        put?: never;
        /** 新增常用参赛人 */
        post: operations["appCreateProfile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/app/profiles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 修改常用参赛人；idNo 省略或为空串时保留原证件号 */
        put: operations["appUpdateProfile"];
        post?: never;
        /** 删除常用参赛人 */
        delete: operations["appDeleteProfile"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/app/consents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 当前生效的同意书版本；所请求语言没有时依次回退到英文、中文 */
        get: operations["appGetConsent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            error: {
                code: string;
                message: string;
                fields?: {
                    [key: string]: string;
                };
            };
        };
        Health: {
            status: string;
        };
        /** @enum {string} */
        Role: "ADMIN" | "OPS" | "FINANCE" | "SUPPORT" | "RACE_SUPERVISOR" | "RACE_STAFF" | "PHOTOGRAPHER";
        /** @enum {string} */
        Access: "read" | "write";
        Staff: {
            /** Format: int64 */
            id: number;
            username: string;
            fullName: string;
            role: components["schemas"]["Role"];
        };
        Me: {
            staff: components["schemas"]["Staff"];
            permissions: {
                [key: string]: components["schemas"]["Access"];
            };
        };
        LoginRequest: {
            username: string;
            password: string;
        };
        LocalizedText: {
            zh?: string;
            en?: string;
            km?: string;
        };
        PublicCategory: {
            code: string;
            name: string;
            /** Format: int32 */
            distanceM: number;
            /** Format: int32 */
            capacity: number;
            /** Format: date-time */
            startAt: string;
            /** Format: date-time */
            cutoffAt: string;
        };
        PublicEvent: {
            slug: string;
            name: string;
            city: string;
            /** Format: date */
            raceDate: string;
            categories: components["schemas"]["PublicCategory"][];
        };
        PublicEventList: {
            items: components["schemas"]["PublicEvent"][];
        };
        AdminCategory: {
            /** Format: int64 */
            id: number;
            code: string;
            name: components["schemas"]["LocalizedText"];
            /** Format: int32 */
            distanceM: number;
            /** Format: int32 */
            capacity: number;
            /** Format: date-time */
            startAt: string | null;
            /** Format: date-time */
            cutoffAt: string | null;
        };
        AdminEvent: {
            /** Format: int64 */
            id: number;
            slug: string;
            /** @enum {string} */
            eventType: "RACE" | "FREE_ACTIVITY";
            /** @enum {string} */
            organizerType: "OFFICIAL" | "PARTNER";
            name: components["schemas"]["LocalizedText"];
            city: string;
            /** Format: date */
            raceDate: string;
            /** @enum {string} */
            status: "DRAFT" | "PUBLISHED";
            publicVisible: boolean;
            /** Format: date-time */
            publishedAt: string | null;
            timezone: string;
            registrationOpen: boolean;
            /** Format: date-time */
            registrationOpensAt: string | null;
            /** Format: date-time */
            registrationClosesAt: string | null;
            categories: components["schemas"]["AdminCategory"][];
        };
        AdminEventList: {
            items: components["schemas"]["AdminEvent"][];
        };
        UpdateEventRegistrationRequest: {
            open: boolean;
            /** Format: date-time */
            opensAt?: string | null;
            /** Format: date-time */
            closesAt?: string | null;
        };
        CreateCategoryRequest: {
            code: string;
            name: components["schemas"]["LocalizedText"];
            /** Format: int32 */
            distanceM: number;
            /** Format: int32 */
            capacity: number;
            /** Format: date-time */
            startAt?: string | null;
            /** Format: date-time */
            cutoffAt?: string | null;
        };
        CreateEventRequest: {
            slug: string;
            /** @enum {string} */
            eventType: "RACE" | "FREE_ACTIVITY";
            /** @enum {string} */
            organizerType: "OFFICIAL" | "PARTNER";
            name: components["schemas"]["LocalizedText"];
            city: string;
            /** Format: date */
            raceDate: string;
            categories: components["schemas"]["CreateCategoryRequest"][];
        };
        /** @enum {string} */
        PriceAudience: "ALL" | "LOCAL";
        PriceRuleInput: {
            name: components["schemas"]["LocalizedText"];
            audience: components["schemas"]["PriceAudience"];
            /** Format: int64 */
            priceCents: number;
            /** Format: int32 */
            quota?: number | null;
            /** Format: date-time */
            saleStartsAt?: string | null;
            /** Format: date-time */
            saleEndsAt?: string | null;
            /** Format: int32 */
            sortOrder?: number;
            categoryIds: number[];
        };
        PriceRule: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            eventId: number;
            name: components["schemas"]["LocalizedText"];
            audience: components["schemas"]["PriceAudience"];
            /** Format: int64 */
            priceCents: number;
            currency: string;
            /** Format: int32 */
            quota: number | null;
            /** Format: date-time */
            saleStartsAt: string | null;
            /** Format: date-time */
            saleEndsAt: string | null;
            /** Format: int32 */
            sortOrder: number;
            categoryIds: number[];
            /** Format: int32 */
            usedCount: number;
            /** Format: int32 */
            reservedCount: number;
        };
        PriceRuleList: {
            items: components["schemas"]["PriceRule"][];
        };
        /** @enum {string} */
        DiscountType: "PERCENT" | "AMOUNT" | "WAIVER";
        /** @enum {string} */
        CouponStatus: "ACTIVE" | "DISABLED";
        UpdateCouponRequest: {
            /** Format: int64 */
            eventId?: number | null;
            discountType: components["schemas"]["DiscountType"];
            /**
             * Format: int64
             * @description PERCENT 为 1–100；AMOUNT 为美分；WAIVER 为 0
             */
            discountValue: number;
            /** Format: int32 */
            quota: number;
            /** Format: int32 */
            minRunners?: number | null;
            /** Format: date-time */
            validFrom?: string | null;
            /** Format: date-time */
            validUntil?: string | null;
            description?: components["schemas"]["LocalizedText"];
            status: components["schemas"]["CouponStatus"];
        };
        CreateCouponRequest: {
            code: string;
            /** Format: int64 */
            eventId?: number | null;
            discountType: components["schemas"]["DiscountType"];
            /** Format: int64 */
            discountValue: number;
            /** Format: int32 */
            quota: number;
            /** Format: int32 */
            minRunners?: number | null;
            /** Format: date-time */
            validFrom?: string | null;
            /** Format: date-time */
            validUntil?: string | null;
            description?: components["schemas"]["LocalizedText"];
            status: components["schemas"]["CouponStatus"];
        };
        Coupon: {
            /** Format: int64 */
            id: number;
            code: string;
            /** Format: int64 */
            eventId: number | null;
            discountType: components["schemas"]["DiscountType"];
            /** Format: int64 */
            discountValue: number;
            /** Format: int32 */
            quota: number;
            /** Format: int32 */
            minRunners: number | null;
            /** Format: date-time */
            validFrom: string | null;
            /** Format: date-time */
            validUntil: string | null;
            description?: components["schemas"]["LocalizedText"];
            status: components["schemas"]["CouponStatus"];
            /** Format: int32 */
            usedCount: number;
            /** Format: int32 */
            reservedCount: number;
        };
        CouponList: {
            items: components["schemas"]["Coupon"][];
        };
        /** @enum {string} */
        PaymentProvider: "ABA" | "ACLEDA" | "WING" | "BAKONG" | "OTHER";
        /** @enum {string} */
        PaymentAccountScope: "REGISTRATION" | "MERCH" | "ALL";
        PaymentAccount: {
            /** Format: int64 */
            id: number;
            name: string;
            provider: components["schemas"]["PaymentProvider"];
            accountName: string;
            accountNoMasked: string;
            currency: string;
            /**
             * Format: int64
             * @description 二维码地址为 /api/files/{qrFileId}
             */
            qrFileId: number;
            scope: components["schemas"]["PaymentAccountScope"];
            /** Format: int64 */
            eventId: number | null;
            active: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        PaymentAccountList: {
            items: components["schemas"]["PaymentAccount"][];
        };
        AppLoginRequest: {
            initData: string;
        };
        AppUser: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            telegramUserId: number;
            telegramUsername: string;
            displayName: string;
            /** @enum {string} */
            locale: "zh" | "en" | "km";
        };
        AppSession: {
            token: string;
            /** Format: date-time */
            expiresAt: string;
            user: components["schemas"]["AppUser"];
        };
        /** @enum {string} */
        Gender: "M" | "F" | "X";
        /** @enum {string} */
        IdType: "NATIONAL_ID" | "PASSPORT" | "OTHER";
        /** @enum {string} */
        TShirtSize: "XS" | "S" | "M" | "L" | "XL" | "XXL";
        ProfileInput: {
            fullName: string;
            gender: components["schemas"]["Gender"];
            /** Format: date */
            birthDate: string;
            /** @description ISO 3166-1 alpha-2，如 KH */
            nationality: string;
            idType: components["schemas"]["IdType"];
            /** @description 新建时必填；修改时省略或为空串表示保留原证件号 */
            idNo?: string;
            /** @description E.164，如 +85512345678 */
            phone: string;
            email?: string;
            emergencyName: string;
            emergencyPhone: string;
            tshirtSize: components["schemas"]["TShirtSize"];
            /** @default false */
            isSelf: boolean;
        };
        RunnerProfile: {
            /** Format: int64 */
            id: number;
            fullName: string;
            gender: components["schemas"]["Gender"];
            /** Format: date */
            birthDate: string;
            nationality: string;
            idType: components["schemas"]["IdType"];
            /** @description 只保留后 4 位，其余为 * */
            idNoMasked: string;
            phone: string;
            /** @description 未填写时为空串 */
            email: string;
            emergencyName: string;
            emergencyPhone: string;
            tshirtSize: components["schemas"]["TShirtSize"];
            isSelf: boolean;
        };
        RunnerProfileList: {
            items: components["schemas"]["RunnerProfile"][];
        };
        ConsentItem: {
            key: string;
            title: string;
            /** @description 没有说明时为空串 */
            description: string;
        };
        ConsentVersion: {
            version: string;
            /** @description 实际返回的语言，可能是回退后的 en 或 zh；签署时原样提交 */
            lang: string;
            /** Format: date */
            effectiveDate: string;
            fullText: string;
            items: components["schemas"]["ConsentItem"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 进程存活 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description 错误 */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getReadyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 可以接收流量 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description 数据库不可用 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description 错误 */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    adminLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description 登录成功，响应头 Set-Cookie 下发 werun_admin_session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            /** @description 错误 */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    adminLogout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已退出 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 错误 */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    adminGetMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 当前员工 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            /** @description 错误 */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listPublicEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 赛事列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicEventList"];
                };
            };
            /** @description 错误 */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getPublicEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 赛事详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicEvent"];
                };
            };
            /** @description 错误 */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    adminListEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 赛事列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminEventList"];
                };
            };
            /** @description 错误 */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    adminCreateEvent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEventRequest"];
            };
        };
        responses: {
            /** @description 已创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminEvent"];
                };
            };
            /** @description 错误 */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    adminGetEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 赛事详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminEvent"];
                };
            };
            /** @description 错误 */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    adminUpdateEventRegistration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEventRegistrationRequest"];
            };
        };
        responses: {
            /** @description 已保存 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminEvent"];
                };
            };
            /** @description 错误（未就绪时为 422 REGISTRATION_NOT_READY） */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    adminPublishEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已发布 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminEvent"];
                };
            };
            /** @description 错误 */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    adminListPriceRules: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 价格档列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriceRuleList"];
                };
            };
            /** @description 错误 */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    adminCreatePriceRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PriceRuleInput"];
            };
        };
        responses: {
            /** @description 已创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriceRule"];
                };
            };
            /** @description 错误 */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    adminUpdatePriceRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PriceRuleInput"];
            };
        };
        responses: {
            /** @description 已保存 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriceRule"];
                };
            };
            /** @description 错误 */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    adminListCoupons: {
        parameters: {
            query?: {
                eventId?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 优惠码列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CouponList"];
                };
            };
            /** @description 错误 */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    adminCreateCoupon: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCouponRequest"];
            };
        };
        responses: {
            /** @description 已创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Coupon"];
                };
            };
            /** @description 错误 */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    adminUpdateCoupon: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCouponRequest"];
            };
        };
        responses: {
            /** @description 已保存 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Coupon"];
                };
            };
            /** @description 错误 */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getPublicFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 图片内容 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/*": string;
                };
            };
            /** @description 错误 */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    adminListPaymentAccounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 收款账户列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentAccountList"];
                };
            };
            /** @description 错误 */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    adminCreatePaymentAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    name: string;
                    provider: components["schemas"]["PaymentProvider"];
                    accountName: string;
                    accountNoMasked: string;
                    scope: components["schemas"]["PaymentAccountScope"];
                    /** @description 绑定的赛事 id；空串或缺省表示全局 */
                    eventId?: string;
                    /** @enum {string} */
                    active: "true" | "false";
                    /**
                     * Format: binary
                     * @description 收款二维码图片，JPEG / PNG / WebP，≤ 2 MB
                     */
                    qr: string;
                };
            };
        };
        responses: {
            /** @description 已创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentAccount"];
                };
            };
            /** @description 错误 */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    adminUpdatePaymentAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    name: string;
                    provider: components["schemas"]["PaymentProvider"];
                    accountName: string;
                    accountNoMasked: string;
                    scope: components["schemas"]["PaymentAccountScope"];
                    /** @description 绑定的赛事 id；空串或缺省表示全局 */
                    eventId?: string;
                    /** @enum {string} */
                    active: "true" | "false";
                    /** Format: binary */
                    qr?: string;
                };
            };
        };
        responses: {
            /** @description 已保存 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentAccount"];
                };
            };
            /** @description 错误 */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    appLoginTelegram: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppLoginRequest"];
            };
        };
        responses: {
            /** @description 登录成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppSession"];
                };
            };
            /** @description 错误 */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    appLogout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已退出 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 错误 */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    appGetMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 当前跑者 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppUser"];
                };
            };
            /** @description 错误 */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    appListProfiles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 常用参赛人列表，本人排在最前 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunnerProfileList"];
                };
            };
            /** @description 错误 */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    appCreateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileInput"];
            };
        };
        responses: {
            /** @description 已创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunnerProfile"];
                };
            };
            /** @description 错误 */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    appUpdateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileInput"];
            };
        };
        responses: {
            /** @description 已修改 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunnerProfile"];
                };
            };
            /** @description 错误 */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    appDeleteProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已删除 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 错误 */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    appGetConsent: {
        parameters: {
            query: {
                purpose: "REGISTRATION";
                lang?: "zh" | "en" | "km";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 当前生效的同意书 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsentVersion"];
                };
            };
            /** @description 错误 */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
