/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 进程存活检查 */
        get: operations["getHealthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 数据库连通检查 */
        get: operations["getReadyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 员工登录 */
        post: operations["adminLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 退出登录 */
        post: operations["adminLogout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 当前员工与权限 */
        get: operations["adminGetMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 已发布且公开展示的赛事列表，文案按请求语言返回 */
        get: operations["listPublicEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 赛事详情（含组别） */
        get: operations["getPublicEvent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 后台赛事列表（名称返回三语） */
        get: operations["adminListEvents"];
        put?: never;
        /** 新建草稿赛事及组别 */
        post: operations["adminCreateEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/events/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 后台赛事详情（任意状态，含报名设置与组别） */
        get: operations["adminGetEvent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/events/{id}/registration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 修改报名开关与报名时间（开放前校验发布状态、价格档与收款账户） */
        patch: operations["adminUpdateEventRegistration"];
        trace?: never;
    };
    "/admin/events/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 发布赛事（发布前校验） */
        post: operations["adminPublishEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            error: {
                code: string;
                message: string;
                fields?: {
                    [key: string]: string;
                };
            };
        };
        Health: {
            status: string;
        };
        /** @enum {string} */
        Role: "ADMIN" | "OPS" | "FINANCE" | "SUPPORT" | "RACE_SUPERVISOR" | "RACE_STAFF" | "PHOTOGRAPHER";
        /** @enum {string} */
        Access: "read" | "write";
        Staff: {
            /** Format: int64 */
            id: number;
            username: string;
            fullName: string;
            role: components["schemas"]["Role"];
        };
        Me: {
            staff: components["schemas"]["Staff"];
            permissions: {
                [key: string]: components["schemas"]["Access"];
            };
        };
        LoginRequest: {
            username: string;
            password: string;
        };
        LocalizedText: {
            zh?: string;
            en?: string;
            km?: string;
        };
        PublicCategory: {
            code: string;
            name: string;
            /** Format: int32 */
            distanceM: number;
            /** Format: int32 */
            capacity: number;
            /** Format: date-time */
            startAt: string;
            /** Format: date-time */
            cutoffAt: string;
        };
        PublicEvent: {
            slug: string;
            name: string;
            city: string;
            /** Format: date */
            raceDate: string;
            categories: components["schemas"]["PublicCategory"][];
        };
        PublicEventList: {
            items: components["schemas"]["PublicEvent"][];
        };
        AdminCategory: {
            /** Format: int64 */
            id: number;
            code: string;
            name: components["schemas"]["LocalizedText"];
            /** Format: int32 */
            distanceM: number;
            /** Format: int32 */
            capacity: number;
            /** Format: date-time */
            startAt: string | null;
            /** Format: date-time */
            cutoffAt: string | null;
        };
        AdminEvent: {
            /** Format: int64 */
            id: number;
            slug: string;
            /** @enum {string} */
            eventType: "RACE" | "FREE_ACTIVITY";
            /** @enum {string} */
            organizerType: "OFFICIAL" | "PARTNER";
            name: components["schemas"]["LocalizedText"];
            city: string;
            /** Format: date */
            raceDate: string;
            /** @enum {string} */
            status: "DRAFT" | "PUBLISHED";
            publicVisible: boolean;
            /** Format: date-time */
            publishedAt: string | null;
            timezone: string;
            registrationOpen: boolean;
            /** Format: date-time */
            registrationOpensAt: string | null;
            /** Format: date-time */
            registrationClosesAt: string | null;
            categories: components["schemas"]["AdminCategory"][];
        };
        AdminEventList: {
            items: components["schemas"]["AdminEvent"][];
        };
        UpdateEventRegistrationRequest: {
            open: boolean;
            /** Format: date-time */
            opensAt?: string | null;
            /** Format: date-time */
            closesAt?: string | null;
        };
        CreateCategoryRequest: {
            code: string;
            name: components["schemas"]["LocalizedText"];
            /** Format: int32 */
            distanceM: number;
            /** Format: int32 */
            capacity: number;
            /** Format: date-time */
            startAt?: string | null;
            /** Format: date-time */
            cutoffAt?: string | null;
        };
        CreateEventRequest: {
            slug: string;
            /** @enum {string} */
            eventType: "RACE" | "FREE_ACTIVITY";
            /** @enum {string} */
            organizerType: "OFFICIAL" | "PARTNER";
            name: components["schemas"]["LocalizedText"];
            city: string;
            /** Format: date */
            raceDate: string;
            categories: components["schemas"]["CreateCategoryRequest"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 进程存活 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description 错误 */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getReadyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 可以接收流量 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description 数据库不可用 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description 错误 */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    adminLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description 登录成功，响应头 Set-Cookie 下发 werun_admin_session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            /** @description 错误 */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    adminLogout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已退出 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 错误 */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    adminGetMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 当前员工 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            /** @description 错误 */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listPublicEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 赛事列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicEventList"];
                };
            };
            /** @description 错误 */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getPublicEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 赛事详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicEvent"];
                };
            };
            /** @description 错误 */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    adminListEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 赛事列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminEventList"];
                };
            };
            /** @description 错误 */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    adminCreateEvent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEventRequest"];
            };
        };
        responses: {
            /** @description 已创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminEvent"];
                };
            };
            /** @description 错误 */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    adminGetEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 赛事详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminEvent"];
                };
            };
            /** @description 错误 */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    adminUpdateEventRegistration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEventRegistrationRequest"];
            };
        };
        responses: {
            /** @description 已保存 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminEvent"];
                };
            };
            /** @description 错误（未就绪时为 422 REGISTRATION_NOT_READY） */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    adminPublishEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已发布 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminEvent"];
                };
            };
            /** @description 错误 */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
