// Command permgen 读取 openapi.yaml，生成「接口 → 鉴权规则」映射表 apigen/permissions.gen.go。
//
// 规则：
//   - 路径以 /admin/ 开头的操作必须声明 x-auth（none | session），或同时声明 x-permission 与 x-access（read | write）；
//   - 其它（公开）操作不得声明这三个扩展字段，映射为 AuthNone；
//   - 映射表的键是 strict 中间件收到的 operationID：oapi-codegen 把 operationId 转成首字母大写的驼峰（adminLogin → AdminLogin）。
package main

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strings"
	"text/template"
	"unicode"

	"github.com/getkin/kin-openapi/openapi3"
)

const adminPrefix = "/admin/"

type rule struct {
	Kind       string // Go 常量名：AuthNone / AuthSession / AuthPermission
	Permission string
	Access     string
}

func main() {
	spec := flag.String("spec", "openapi/openapi.yaml", "OpenAPI 规范文件路径")
	out := flag.String("out", "internal/httpapi/apigen/permissions.gen.go", "生成文件路径")
	flag.Parse()
	if err := run(*spec, *out); err != nil {
		fmt.Fprintln(os.Stderr, "permgen:", err)
		os.Exit(1)
	}
}

func run(specPath, outPath string) error {
	data, err := os.ReadFile(specPath)
	if err != nil {
		return err
	}
	rules, err := build(data)
	if err != nil {
		return err
	}
	src, err := render(rules)
	if err != nil {
		return err
	}
	return os.WriteFile(outPath, src, 0o644)
}

func build(data []byte) (map[string]rule, error) {
	doc, err := openapi3.NewLoader().LoadFromData(data)
	if err != nil {
		return nil, fmt.Errorf("解析 OpenAPI 失败: %w", err)
	}
	rules := map[string]rule{}
	var problems []string
	for path, item := range doc.Paths.Map() {
		for method, op := range item.Operations() {
			where := method + " " + path
			if op.OperationID == "" {
				problems = append(problems, where+": 缺少 operationId")
				continue
			}
			name := strictName(op.OperationID)
			if _, dup := rules[name]; dup {
				problems = append(problems, fmt.Sprintf("%s (%s): operationId 重复", where, op.OperationID))
				continue
			}
			r, err := ruleFor(path, op.Extensions)
			if err != nil {
				problems = append(problems, fmt.Sprintf("%s (%s): %v", where, op.OperationID, err))
				continue
			}
			rules[name] = r
		}
	}
	if len(problems) > 0 {
		sort.Strings(problems)
		return nil, errors.New(strings.Join(problems, "\n"))
	}
	return rules, nil
}

func ruleFor(path string, ext map[string]any) (rule, error) {
	auth, hasAuth, errAuth := stringExt(ext, "x-auth")
	perm, hasPerm, errPerm := stringExt(ext, "x-permission")
	access, hasAccess, errAccess := stringExt(ext, "x-access")
	if err := errors.Join(errAuth, errPerm, errAccess); err != nil {
		return rule{}, err
	}

	if !strings.HasPrefix(path, adminPrefix) {
		if hasAuth || hasPerm || hasAccess {
			return rule{}, errors.New("公开接口不能声明 x-auth / x-permission / x-access")
		}
		return rule{Kind: "AuthNone"}, nil
	}

	switch {
	case hasAuth && (hasPerm || hasAccess):
		return rule{}, errors.New("x-auth 不能与 x-permission / x-access 同时声明")
	case hasAuth:
		switch auth {
		case "none":
			return rule{Kind: "AuthNone"}, nil
		case "session":
			return rule{Kind: "AuthSession"}, nil
		default:
			return rule{}, fmt.Errorf("x-auth 只能是 none 或 session，实际为 %q", auth)
		}
	case hasPerm:
		if perm == "" {
			return rule{}, errors.New("x-permission 不能为空")
		}
		if !hasAccess {
			return rule{}, errors.New("声明了 x-permission 但缺少 x-access")
		}
		if access != "read" && access != "write" {
			return rule{}, fmt.Errorf("x-access 只能是 read 或 write，实际为 %q", access)
		}
		return rule{Kind: "AuthPermission", Permission: perm, Access: access}, nil
	default:
		return rule{}, errors.New("后台接口必须声明 x-auth，或同时声明 x-permission 与 x-access")
	}
}

func stringExt(ext map[string]any, key string) (string, bool, error) {
	v, ok := ext[key]
	if !ok {
		return "", false, nil
	}
	s, isString := v.(string)
	if !isString {
		return "", true, fmt.Errorf("%s 必须是字符串", key)
	}
	return s, true, nil
}

// strictName 与 oapi-codegen 的命名一致：按非字母数字切分，每段首字母大写后拼接。
func strictName(operationID string) string {
	parts := strings.FieldsFunc(operationID, func(r rune) bool {
		return !unicode.IsLetter(r) && !unicode.IsDigit(r)
	})
	var b strings.Builder
	for _, p := range parts {
		runes := []rune(p)
		runes[0] = unicode.ToUpper(runes[0])
		b.WriteString(string(runes))
	}
	return b.String()
}

type entry struct {
	Name string
	rule
}

var fileTemplate = template.Must(template.New("permissions").Parse(`// Code generated by permgen from openapi/openapi.yaml. DO NOT EDIT.

package apigen

// AuthKind 表示一个接口需要的鉴权方式。
type AuthKind string

const (
	AuthNone       AuthKind = "none"
	AuthSession    AuthKind = "session"
	AuthPermission AuthKind = "permission"
)

// OperationAuth 是单个接口的鉴权规则。
type OperationAuth struct {
	Kind       AuthKind
	Permission string
	Access     string
}

// OperationAuths 的键是 strict 中间件收到的 operationID（首字母大写的 operationId）。
var OperationAuths = map[string]OperationAuth{
{{- range .}}
	{{printf "%q" .Name}}: {Kind: {{.Kind}}{{if .Permission}}, Permission: {{printf "%q" .Permission}}, Access: {{printf "%q" .Access}}{{end}}},
{{- end}}
}
`))

func render(rules map[string]rule) ([]byte, error) {
	entries := make([]entry, 0, len(rules))
	for name, r := range rules {
		entries = append(entries, entry{Name: name, rule: r})
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].Name < entries[j].Name })

	var buf bytes.Buffer
	if err := fileTemplate.Execute(&buf, entries); err != nil {
		return nil, err
	}
	return format.Source(buf.Bytes())
}
