package main

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

const validSpec = `
openapi: 3.0.3
info: {title: t, version: "1"}
paths:
  /healthz:
    get:
      operationId: getHealthz
      responses: {"200": {description: ok}}
  /admin/auth/login:
    post:
      operationId: adminLogin
      x-auth: none
      responses: {"200": {description: ok}}
  /admin/me:
    get:
      operationId: adminGetMe
      x-auth: session
      responses: {"200": {description: ok}}
  /admin/events:
    post:
      operationId: adminCreateEvent
      x-permission: event_config
      x-access: write
      responses: {"201": {description: ok}}
  /app/auth/telegram:
    post:
      operationId: appLoginTelegram
      x-auth: none
      responses: {"200": {description: ok}}
  /app/me:
    get:
      operationId: appGetMe
      x-auth: app
      responses: {"200": {description: ok}}
`

func TestBuildValidSpec(t *testing.T) {
	rules, err := build([]byte(validSpec))
	require.NoError(t, err)
	assert.Equal(t, map[string]rule{
		"GetHealthz":       {Kind: "AuthNone"},
		"AdminLogin":       {Kind: "AuthNone"},
		"AdminGetMe":       {Kind: "AuthSession"},
		"AdminCreateEvent": {Kind: "AuthPermission", Permission: "event_config", Access: "write"},
		"AppLoginTelegram": {Kind: "AuthNone"},
		"AppGetMe":         {Kind: "AuthApp"},
	}, rules)
}

func specWithOp(path, extensions string) string {
	return `
openapi: 3.0.3
info: {title: t, version: "1"}
paths:
  ` + path + `:
    post:
      operationId: doThing
` + extensions + `
      responses: {"200": {description: ok}}
`
}

func specWithAdminOp(extensions string) string {
	return specWithOp("/admin/things", extensions)
}

func TestBuildRejectsInvalidExtensions(t *testing.T) {
	cases := []struct {
		name       string
		spec       string
		wantSubstr string
	}{
		{"admin op without extensions", specWithAdminOp(""), "后台接口必须声明 x-auth"},
		{"permission without access", specWithAdminOp("      x-permission: event_config"), "缺少 x-access"},
		{"invalid access", specWithAdminOp("      x-permission: event_config\n      x-access: admin"), "x-access 只能是 read 或 write"},
		{"invalid x-auth", specWithAdminOp("      x-auth: maybe"), "x-auth 只能是 none 或 session"},
		{"x-auth with permission", specWithAdminOp("      x-auth: session\n      x-permission: event_config\n      x-access: read"), "不能与 x-permission"},
		{"admin op with x-auth app", specWithAdminOp("      x-auth: app"), "x-auth: app 只能用于 /app/ 下的接口"},
		{"app op without x-auth", specWithOp("/app/things", ""), "跑者接口必须声明 x-auth"},
		{"app op with session", specWithOp("/app/things", "      x-auth: session"), "跑者接口的 x-auth 只能是 none 或 app"},
		{"app op with permission", specWithOp("/app/things", "      x-auth: app\n      x-permission: event_config\n      x-access: read"), "跑者接口不能声明 x-permission / x-access"},
		{"app op with access only", specWithOp("/app/things", "      x-access: read"), "跑者接口不能声明 x-permission / x-access"},
		{"public op with permission", `
openapi: 3.0.3
info: {title: t, version: "1"}
paths:
  /events:
    get:
      operationId: listPublicEvents
      x-permission: event_config
      x-access: read
      responses: {"200": {description: ok}}
`, "公开接口不能声明"},
		{"public op with x-auth app", specWithOp("/files/things", "      x-auth: app"), "公开接口不能声明"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			_, err := build([]byte(tc.spec))
			require.Error(t, err)
			assert.Contains(t, err.Error(), tc.wantSubstr)
		})
	}
}

func TestBuildReportsOperationID(t *testing.T) {
	_, err := build([]byte(specWithAdminOp("")))
	require.Error(t, err)
	assert.Contains(t, err.Error(), "doThing")
	assert.Contains(t, err.Error(), "POST /admin/things")
}

func TestStrictName(t *testing.T) {
	assert.Equal(t, "AdminLogin", strictName("adminLogin"))
	assert.Equal(t, "GetHealthz", strictName("getHealthz"))
	assert.Equal(t, "AdminPublishEvent", strictName("admin-publish_event"))
	assert.Equal(t, "AppLoginTelegram", strictName("appLoginTelegram"))
}

func TestRenderIsDeterministicAndFormatted(t *testing.T) {
	rules, err := build([]byte(validSpec))
	require.NoError(t, err)

	first, err := render(rules)
	require.NoError(t, err)
	second, err := render(rules)
	require.NoError(t, err)
	assert.Equal(t, string(first), string(second))

	src := string(first)
	assert.True(t, strings.HasPrefix(src, "// Code generated by permgen"))
	assert.Contains(t, src, "package apigen")
	assert.Contains(t, src, `AuthApp        AuthKind = "app"`)
	assert.Contains(t, src, `{Kind: AuthPermission, Permission: "event_config", Access: "write"}`)
	assert.Contains(t, src, `{Kind: AuthSession}`)
	assert.Contains(t, src, `"AppGetMe":         {Kind: AuthApp}`)
	assert.Less(t, strings.Index(src, `"AdminCreateEvent"`), strings.Index(src, `"GetHealthz"`))
}
